# no normalizing version


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = np.genfromtxt('data_outlier little_timeless.txt')

np.random.seed(4)
np.random.shuffle(data)

X = data[:,0:5]
Y = data[:,5:16]
dfX=pd.DataFrame(X)
dfy=pd.DataFrame(Y)

table=pd.concat([dfX, dfy], axis=1)
table.columns=['SiH4','N2O','Temp','Pressure','RF Power','Thickness','Depo. Rate','Uniformity','Ref. Index','Permittivity','Etch Rate','Stress','H2O','SiOH']

In [3]:
print(table)

     SiH4    N2O   Temp  Pressure  RF Power  Thickness  Depo. Rate  \
0   667.0  333.0  375.0       2.0     150.0        4.0       749.0   
1   200.0  400.0  200.0       0.0     150.0        6.0       287.0   
2   400.0  400.0  200.0       2.0     150.0        5.0       352.0   
3   400.0  900.0  200.0       1.0      20.0        6.0       375.0   
4   400.0  900.0  150.0       2.0      80.0        5.0       409.0   
5   400.0  400.0  200.0       0.0      20.0        5.0       139.0   
6   400.0  900.0  250.0       1.0      80.0        5.0       587.0   
7   333.0  667.0  375.0       2.0     150.0        2.0       331.0   
8   200.0  400.0  400.0       0.0      20.0        6.0       123.0   
9   300.0  650.0  300.0       1.0      85.0        5.0       433.0   
10  400.0  900.0  400.0       0.0      20.0        3.0        56.0   
11  400.0  900.0  400.0       2.0     150.0        5.0       426.0   
12  200.0  400.0  400.0       2.0     150.0        5.0       173.0   
13  200.0  900.0  20

In [4]:
X_train = X[0:23,:]
Y_train = Y[0:23,0]
X_test = X[23:28,:]
Y_test = Y[23:28,0]

## Gradient Boosting Regression

In [5]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error

In [6]:
params = {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 4,
          'learning_rate': 0.005, 'loss': 'ls'}

GBR = ensemble.GradientBoostingRegressor(**params)

GBR.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, GBR.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 0.5554


In [7]:
print(Y_test)
print(GBR.predict(X_test))

[5. 6. 5. 5. 5.]
[3.75420773 5.92874269 4.73476302 5.53591565 5.92874269]


## Support Vecter Regression

### rbf kernel?


In [8]:
import numpy as np
from sklearn.svm import SVR

In [9]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)

svr_rbf.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_rbf.predict(X_test))
print("MSE: %.4f" % mse)

MSE: 0.5746


In [ ]:
print(Y_test)
print(svr_rbf.predict(X_test))

[5. 6. 5. 5. 5.]
[4.55610644 4.55610644 4.55610644 4.55610644 4.55610644]


### no kernel?


In [ ]:
svr_lin = SVR(kernel='linear', C=1e3)

svr_lin.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_lin.predict(X_test))
print("MSE: %.4f" % mse)


In [ ]:
print(Y_test)
print(svr_lin.predict(X_test))

## Decision Tree Regression
### basic

In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [ ]:
regr_1 = DecisionTreeRegressor(max_depth=4)

regr_1.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_1.predict(X_test))
print("MSE: %.4f" % mse)



In [ ]:
print(Y_test)
print(regr_1.predict(X_test))


### with AdaBoost

In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [ ]:
rng = np.random.RandomState(1)


regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=4),
                           n_estimators=300, random_state=rng)
regr_2.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_2.predict(X_test))
print("MSE: %.4f" % mse)




In [ ]:
print(Y_test)
print(regr_2.predict(X_test))