# no normalizing version


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = np.genfromtxt('data.txt')

np.random.seed(4)
np.random.shuffle(data)

X = data[:,0:6]
Y = data[:,6:16]
dfX=pd.DataFrame(X)
dfy=pd.DataFrame(Y)

table=pd.concat([dfX, dfy], axis=1)
table.columns=['SiH4','N2O','Temp','Pressure','RF Power','Time','Thickness','Depo. Rate','Uniformity','Ref. Index','Permittivity','Etch Rate','Stress','H2O','SiOH']

In [3]:
print(table)

     SiH4     N2O   Temp  Pressure  RF Power   Time  Thickness  Depo. Rate  \
0   400.0   900.0  400.0      0.25      20.0  600.0       3.36        56.0   
1   333.0   667.0  375.0      1.80     150.0   60.0       1.98       331.0   
2   400.0   400.0  200.0      0.25      20.0  381.0       5.29       139.0   
3   833.0   167.0  375.0      1.80     150.0   45.0       4.52      1005.0   
4   400.0   900.0  200.0      0.50      80.0  164.0       5.31       324.0   
5   200.0   400.0  200.0      0.25     150.0  192.0       5.52       287.0   
6   400.0   900.0  200.0      1.80     150.0  126.0       4.99       396.0   
7   667.0   333.0  375.0      1.80     150.0   60.0       4.49       749.0   
8   400.0   400.0  400.0      0.25     150.0  134.0       6.09       454.0   
9   300.0   600.0  375.0      1.80     150.0   65.0       1.95       301.0   
10  400.0   400.0  200.0      1.80     150.0  136.0       4.80       352.0   
11  909.0    91.0  375.0      1.80     150.0   40.0       4.25  

In [4]:
X_train = X[0:31,:]
Y_train = Y[0:31,0]
X_test = X[31:36,:]
Y_test = Y[31:36,0]

## Gradient Boosting Regression

In [5]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error

In [6]:
params = {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 4,
          'learning_rate': 0.005, 'loss': 'ls'}

GBR = ensemble.GradientBoostingRegressor(**params)

GBR.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, GBR.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 3.7496


In [7]:
print(Y_test)
print(GBR.predict(X_test))

[5.12 4.36 0.79 5.1  5.68]
[4.76516757 5.56713929 4.91987311 4.93950502 5.96825782]


## Support Vecter Regression

### rbf kernel?


In [8]:
import numpy as np
from sklearn.svm import SVR

In [9]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)

svr_rbf.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_rbf.predict(X_test))
print("MSE: %.4f" % mse)

MSE: 3.2961


In [10]:
print(Y_test)
print(svr_rbf.predict(X_test))

[5.12 4.36 0.79 5.1  5.68]
[4.65285714 4.65285714 4.65285714 4.65285714 4.65285714]


### no kernel?


In [11]:
svr_lin = SVR(kernel='linear', C=1e3)

svr_lin.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_lin.predict(X_test))
print("MSE: %.4f" % mse)


MSE: 18080.9201


In [12]:
print(Y_test)
print(svr_lin.predict(X_test))

[5.12 4.36 0.79 5.1  5.68]
[153.44006468 212.77195073  61.28700585 150.12908955 -10.96010398]


## Decision Tree Regression
### basic

In [13]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [14]:
regr_1 = DecisionTreeRegressor(max_depth=4)

regr_1.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_1.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 4.0562


In [15]:
print(Y_test)
print(regr_1.predict(X_test))


[5.12 4.36 0.79 5.1  5.68]
[4.745 5.182 5.182 5.182 6.09 ]


### with AdaBoost

In [16]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [17]:
rng = np.random.RandomState(1)


regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=4),
                           n_estimators=300, random_state=rng)
regr_2.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_2.predict(X_test))
print("MSE: %.4f" % mse)




MSE: 3.8080


In [18]:
print(Y_test)
print(regr_2.predict(X_test))

[5.12 4.36 0.79 5.1  5.68]
[5.12857143 5.221      5.0675     5.125      5.71153846]
