# no normalizing version


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
data = np.genfromtxt('data_outlier little.txt')

np.random.seed(4)
np.random.shuffle(data)

X = data[:,0:6]
Y = data[:,6:16]
dfX=pd.DataFrame(X)
dfy=pd.DataFrame(Y)

table=pd.concat([dfX, dfy], axis=1)
table.columns=['SiH4','N2O','Temp','Pressure','RF Power','Time','Thickness','Depo. Rate','Uniformity','Ref. Index','Permittivity','Etch Rate','Stress','H2O','SiOH']

In [15]:
print(table)

     SiH4    N2O   Temp  Pressure  RF Power   Time  Thickness  Depo. Rate  \
0   667.0  333.0  375.0      1.80     150.0   60.0       4.49       749.0   
1   200.0  400.0  200.0      0.25     150.0  192.0       5.52       287.0   
2   400.0  400.0  200.0      1.80     150.0  136.0       4.80       352.0   
3   400.0  900.0  200.0      1.10      20.0  154.0       5.78       375.0   
4   400.0  900.0  150.0      1.80      80.0  128.0       5.23       409.0   
5   400.0  400.0  200.0      0.25      20.0  381.0       5.29       139.0   
6   400.0  900.0  250.0      1.10      80.0   85.0       5.01       587.0   
7   333.0  667.0  375.0      1.80     150.0   60.0       1.98       331.0   
8   200.0  400.0  400.0      0.25      20.0  468.0       5.76       123.0   
9   300.0  650.0  300.0      1.03      85.0  115.0       4.98       433.0   
10  400.0  900.0  400.0      0.25      20.0  600.0       3.36        56.0   
11  400.0  900.0  400.0      1.80     150.0  123.0       5.24       426.0   

In [16]:
X_train = X[0:23,:]
Y_train = Y[0:23,0]
X_test = X[23:28,:]
Y_test = Y[23:28,0]

## Gradient Boosting Regression

In [17]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error

In [18]:
params = {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 4,
          'learning_rate': 0.005, 'loss': 'ls'}

GBR = ensemble.GradientBoostingRegressor(**params)

GBR.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, GBR.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 0.0479


In [19]:
print(Y_test)
print(GBR.predict(X_test))

[5.1  5.68 4.99 4.83 5.14]
[5.35212624 5.97834746 5.18965857 4.95319719 4.96185096]


## Support Vecter Regression

### rbf kernel?


In [20]:
import numpy as np
from sklearn.svm import SVR

In [21]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)

svr_rbf.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_rbf.predict(X_test))
print("MSE: %.4f" % mse)

MSE: 0.3857


In [22]:
print(Y_test)
print(svr_rbf.predict(X_test))

[5.1  5.68 4.99 4.83 5.14]
[4.59714286 4.59714286 4.59714286 4.59714286 4.59714286]


### no kernel?


In [63]:
svr_lin = SVR(kernel='linear', C=1e3)

svr_lin.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_lin.predict(X_test))
print("MSE: %.4f" % mse)


MSE: 16769.4431


In [64]:
print(Y_test)
print(svr_lin.predict(X_test))

[5.1  5.68 4.83]
[ -76.9349877   113.54783365 -173.89638463]


## Decision Tree Regression
### basic

In [23]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [24]:
regr_1 = DecisionTreeRegressor(max_depth=4)

regr_1.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_1.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 0.0803


In [25]:
print(Y_test)
print(regr_1.predict(X_test))


[5.1  5.68 4.99 4.83 5.14]
[5.265      6.09       4.98285714 5.265      5.01      ]


### with AdaBoost

In [26]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [27]:
rng = np.random.RandomState(1)


regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=4),
                           n_estimators=300, random_state=rng)
regr_2.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_2.predict(X_test))
print("MSE: %.4f" % mse)




MSE: 0.0160


In [28]:
print(Y_test)
print(regr_2.predict(X_test))

[5.1  5.68 4.99 4.83 5.14]
[4.94       5.69666667 4.955      5.02       5.01      ]
