# no normalizing version


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = np.genfromtxt('data_normal.txt')

np.random.seed(4)
np.random.shuffle(data)

X = data[:,0:6]
Y = data[:,6:16]
dfX=pd.DataFrame(X)
dfy=pd.DataFrame(Y)

table=pd.concat([dfX, dfy], axis=1)
table.columns=['SiH4','N2O','Temp','Pressure','RF Power','Time','Thickness','Depo. Rate','Uniformity','Ref. Index','Permittivity','Etch Rate','Stress','H2O','SiOH']

In [3]:
print(table)

     SiH4    N2O   Temp  Pressure  RF Power   Time  Thickness  Depo. Rate  \
0   200.0  400.0  400.0      1.80     150.0  281.0       4.86       173.0   
1   300.0  650.0  300.0      1.03      85.0  115.0       4.98       433.0   
2   400.0  400.0  200.0      0.25      20.0  381.0       5.29       139.0   
3   200.0  900.0  200.0      0.25      20.0  569.0       5.75       101.0   
4   300.0  650.0  300.0      1.03      85.0  115.0       4.96       432.0   
5   200.0  400.0  400.0      0.25      20.0  468.0       5.76       123.0   
6   200.0  400.0  200.0      0.25     150.0  192.0       5.52       287.0   
7   200.0  900.0  400.0      0.25     150.0  243.0       5.39       222.0   
8   400.0  400.0  200.0      1.80     150.0  136.0       4.80       352.0   
9   200.0  900.0  200.0      1.80     150.0  261.0       5.12       196.0   
10  400.0  900.0  400.0      1.80     150.0  123.0       5.24       426.0   
11  300.0  650.0  300.0      1.03      85.0  115.0       4.92       428.0   

In [4]:
X_train = X[0:16,:]
Y_train = Y[0:16,0]
X_test = X[16:19,:]
Y_test = Y[16:19,0]

## Gradient Boosting Regression

In [5]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error

In [6]:
params = {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 4,
          'learning_rate': 0.005, 'loss': 'ls'}

GBR = ensemble.GradientBoostingRegressor(**params)

GBR.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, GBR.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 0.0258


In [7]:
print(Y_test)
print(GBR.predict(X_test))

[5.1  5.68 4.83]
[5.03840208 5.9482079  4.86996726]


## Support Vecter Regression

### rbf kernel?


In [8]:
import numpy as np
from sklearn.svm import SVR

In [9]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)

svr_rbf.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_rbf.predict(X_test))
print("MSE: %.4f" % mse)

MSE: 0.1307


In [10]:
print(Y_test)
print(svr_rbf.predict(X_test))

[5.1  5.68 4.83]
[5.13307692 5.13307692 5.13307692]


### no kernel?


In [11]:
svr_lin = SVR(kernel='linear', C=1e3)

svr_lin.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, svr_lin.predict(X_test))
print("MSE: %.4f" % mse)


MSE: 16769.4431


In [12]:
print(Y_test)
print(svr_lin.predict(X_test))

[5.1  5.68 4.83]
[ -76.9349877   113.54783365 -173.89638463]


## Decision Tree Regression
### basic

In [13]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [14]:
regr_1 = DecisionTreeRegressor(max_depth=4)

regr_1.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_1.predict(X_test))
print("MSE: %.4f" % mse)



MSE: 0.3122


In [15]:
print(Y_test)
print(regr_1.predict(X_test))


[5.1  5.68 4.83]
[4.36 6.09 4.36]


### with AdaBoost

In [16]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [17]:
rng = np.random.RandomState(1)


regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=4),
                           n_estimators=300, random_state=rng)
regr_2.fit(X_train, Y_train)
mse = mean_squared_error(Y_test, regr_2.predict(X_test))
print("MSE: %.4f" % mse)




MSE: 0.0372


In [18]:
print(Y_test)
print(regr_2.predict(X_test))

[5.1  5.68 4.83]
[4.95 5.75 5.12]
