In [1]:



from anoGANs import Anomaly_Mnist
from anoGANs import BE_infoGANs_v2
import tensorflow as tf
import os
os.environ["CUDA_VISIBLE_DEVICES"]="1"




In [2]:
data = Anomaly_Mnist()
data.set_anomaly(anomalous_nums =[0,1,2,3,4,5,6,7,8])


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
anomalous number :  [0, 1, 2, 3, 4, 5, 6, 7, 8]
test_normal_data :  (1009, 64, 64, 1)
test_anomalous_data :  (8991, 64, 64, 1)
train_normal_data :  (5454, 64, 64, 1)
train_anomalous_data :  (49546, 64, 64, 1)


In [ ]:
import matplotlib.pyplot as plt

num = 333
plt.imshow( data.test_anomalous_data[num].reshape(64,64), cmap='Greys_r')
plt.colorbar()
plt.show()

In [3]:
sess = tf.Session(config=tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))) 
sess.run(tf.global_variables_initializer())

path = 'test1'
mnist = data
a = BE_infoGANs_v2(sess,path,mnist, GANs_epoch = 1, E_epoch = 1, c_size = 20)
a.GANs_fit()
a.E_fit()
a.report()

D_e : -62.231, D_real_e : 57.758, D_fake_e : 19.437, G_e : 19.889, Q_e : 2.534, new_measure : 78.300, k_curr : 11.092
total time :  39.79331684112549
E_e : 55.901585
total time :  28.984439373016357
Normalized confusion matrix
[[  1.00000000e+00   0.00000000e+00]
 [  9.99662921e-01   3.37078652e-04]]
Confusion matrix, without normalization
[[1000    0]
 [8897    3]]
Normalized confusion matrix
[[ 1.  0.]
 [ 1.  0.]]
Confusion matrix, without normalization
[[8900    0]
 [1000    0]]
Normalized confusion matrix
[[ 0.9        0.1      ]
 [ 0.3258427  0.6741573]]
Confusion matrix, without normalization
[[ 900  100]
 [2900 6000]]
Normalized confusion matrix
[[  1.00000000e+00   0.00000000e+00]
 [  9.99550562e-01   4.49438202e-04]]
Confusion matrix, without normalization
[[1000    0]
 [8896    4]]
Normalized confusion matrix
[[  3.37078652e-04   9.99662921e-01]
 [  1.00000000e-03   9.99000000e-01]]
Confusion matrix, without normalization
[[   3 8897]
 [   1  999]]
