In [1]:

import os
import matplotlib
matplotlib.use('Agg')
from BE_resGANs_for_OES import Anomaly_OES
from BE_resGANs_for_OES import BE_resGANs_for_OES
import tensorflow as tf
import os
os.environ["CUDA_VISIBLE_DEVICES"]='1'

data = Anomaly_OES()
data. set_anomaly()






test_normal_data :  (560, 128, 128, 1)
test_anomalous_data :  (560, 128, 128, 1)
train_normal_data :  (10584, 128, 128, 1)


In [2]:

sess = tf.Session(config=tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))) 


path = 'test6'
mnist = data
a = BE_resGANs_for_OES(sess,path,mnist,GANs_epoch = 5, E_epoch = 5,D_lr = 2e-5, G_lr = 2e-4,E_lr = 2e-4, 
                       batch_size = 64, gamma = 0.5, lam = 0.001,  minibatch_increase = True, factor_decrease = True,
                      feature_size = 100)
a.GANs_fit()
a.E_fit()
a.report()

D_e : 11.428, D_real_e : 11.959, D_fake_e : 5.513, G_e : 5.814, new_measure : 14.237, k_curr : 0.109
D_e : 4.078, D_real_e : 4.224, D_fake_e : 2.065, G_e : 2.380, new_measure : 4.677, k_curr : 0.021
D_e : 2.827, D_real_e : 2.879, D_fake_e : 1.162, G_e : 1.164, new_measure : 3.154, k_curr : 0.066
D_e : 2.688, D_real_e : 2.789, D_fake_e : 1.213, G_e : 1.217, new_measure : 2.979, k_curr : 0.096
D_e : 2.595, D_real_e : 2.729, D_fake_e : 1.272, G_e : 1.273, new_measure : 2.854, k_curr : 0.111
total time :  483.8327524662018
E_e : 3.478177
E_e : 3.170230
E_e : 3.113113
E_e : 3.083422
E_e : 3.056670
total time :  174.703364610672
Normalized confusion matrix
[[ 0.55078125  0.44921875]
 [ 0.04882812  0.95117188]]
Confusion matrix, without normalization
[[282 230]
 [ 25 487]]
Normalized confusion matrix
[[ 0.63671875  0.36328125]
 [ 0.00976562  0.99023438]]
Confusion matrix, without normalization
[[326 186]
 [  5 507]]
Normalized confusion matrix
[[ 0.625  0.375]
 [ 0.     1.   ]]
Confusion matr

In [3]:
import tensorflow as tf
tf.__version__


'1.6.0'