In [2]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
import random

os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [3]:
#Power Pressure Gas1 Gas2
data = pd.read_excel('2nd.xlsx') # MLMH
data = data.values
RealOESdata = data[151:251,1:]
data = pd.read_excel('4th.xlsx') # LMHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('6th.xlsx') # HMMH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('8th.xlsx') # HMMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('10th.xlsx') # MLLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('12th.xlsx') # LMML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('14th.xlsx') # MLHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('16th.xlsx') # HMML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('17th.xlsx') # LMLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('21th.xlsx') # HMHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('23th.xlsx') # MLML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('24th.xlsx') # HMLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('25th.xlsx') # LMMH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
####
data = pd.read_excel('1st.xlsx') # MMHH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('7th.xlsx') # MMLH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('15th.xlsx') # LHMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('22th.xlsx') # MHLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('26th.xlsx') # MMMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))



In [54]:
Y_ClassifiedResult = np.array([1, 0, 1, 2])
for k in range(99):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 1, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 1, 2])))
##############################################
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 2, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 0, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 2, 1, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 2, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 1, 1])))
    
Sequence = np.array([0])
for k in range(179):
    Sequence = np.hstack((Sequence, np.array([k+1])))

Sequence
#Y_ClassifiedResult = np.array([[1, 0, 1, 2],
#                            [0, 1, 2, 1],
#                            [2, 1, 1, 2],
#                            [2, 1, 1, 1],
#                            [1, 0, 0, 1],
#                            [0, 1, 1, 0],
#                            [1, 0, 2, 1],
#                            [2, 1, 1, 0],
#                            [0, 1, 0, 1],
#                            [2, 1, 2, 1],
#                            [1, 0, 1, 0],
#                            [2, 1, 0, 1],
#                            [0, 1, 1, 2]])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179])

In [55]:
learning_rate = 0.00005
tf.set_random_seed(777)
batchsize = 10

def build_CNN_classifier(X):
    
    W_conv1 = tf.Variable(tf.truncated_normal(shape=[1, 1, 57, 57], stddev=0.01)) #filter
    # 1 * 1 * image depth * filter 2개
    b_conv1 = tf.Variable(tf.constant(0.1, shape=[57])) #bias
    # convolution filter 갯수에 맞춤 = 2개
    h_conv1 = tf.nn.elu(tf.nn.conv2d(X, W_conv1, strides=[1, 1, 1, 1], padding='VALID') + b_conv1)
    print(h_conv1)
    # convolution 연산 수행. 
    # stride >> 2칸씩 움직이는게 목표라면 [1, 2, 2, 1]로 수정
    # padding >> 'SAME' 이면 stride에 맞추어 최소 size의 padding으로 convolution
    #            'VALID' 이면 stride에 맞추어 계산 가능한 만큼만 계산. 나머지 계산 안된건 버림
    
  # 첫번째 Pooling layer
  #h_pool1 = tf.nn.max_pool(h_conv1, ksize=[1, 3, 3, 1], strides=[1, 2, 2, 1], padding='SAME')
    # 3*3 필터를 2의 stride를 가지고 움직임
    # max pooling

  # 2nd : 8*8*57 -> 5*5*57*114(filter) -> 4*4*114
    W_conv2 = tf.Variable(tf.truncated_normal(shape=[5, 5, 57, 114], stddev=0.01))
    b_conv2 = tf.Variable(tf.constant(0.1, shape=[114]))
    h_conv2 = tf.nn.elu(tf.nn.conv2d(h_conv1, W_conv2, strides=[1, 1, 1, 1], padding='VALID') + b_conv2)
    print(h_conv2)

  # 3rd : 4*4*114 -> 3*3*114*38(filter) -> 2*2*38
    W_conv3 = tf.Variable(tf.truncated_normal(shape=[3, 3, 114, 38], stddev=0.01))
    b_conv3 = tf.Variable(tf.constant(0.1, shape=[38]))
    h_conv3 = tf.nn.elu(tf.nn.conv2d(h_conv2, W_conv3, strides=[1, 1, 1, 1], padding='VALID') + b_conv3)
    print(h_conv3)

  # 2*2*38 -> 8개의 neuron으로 (FCNN)
    W_fc1 = tf.Variable(tf.truncated_normal(shape=[2*2*38, 8], stddev=0.01))
    b_fc1 = tf.Variable(tf.constant(0.1, shape=[8]))
    h_conv4_flat = tf.reshape(h_conv3, [-1, 2*2*38])
    h_fc1 = tf.nn.elu(tf.matmul(h_conv4_flat, W_fc1) + b_fc1)
    print(h_fc1)
    
  # 8 -> 4
    W_fc2 = tf.Variable(tf.truncated_normal(shape=[8, 4], stddev=0.01))
    b_fc2 = tf.Variable(tf.constant(0.1, shape=[4]))
    y_pred = tf.nn.elu(tf.matmul(h_fc1,W_fc2) + b_fc2)
    print(y_pred)

    return y_pred

X = tf.placeholder(tf.float32, shape=[None, 8, 8, 57])
Y = tf.placeholder(tf.float32, shape=[None, 4])

y_pred = build_CNN_classifier(X)

cost = tf.reduce_mean(tf.pow(Y - y_pred, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

Accuracy = y_pred

Tensor("Elu_69:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("Elu_70:0", shape=(?, 4, 4, 114), dtype=float32)
Tensor("Elu_71:0", shape=(?, 2, 2, 38), dtype=float32)
Tensor("Elu_72:0", shape=(?, 8), dtype=float32)
Tensor("Elu_73:0", shape=(?, 4), dtype=float32)


In [59]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range (100001):
        Order = Sequence[step % 180]
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 8, 8, 57))
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 4))
        
        _, MinibatchCost = session.run([train, cost], feed_dict = {X: batch_X, Y: batch_Y})
        
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchCost))
            
        if step % 180 == 0:
            random.shuffle(Sequence)
    
    for i in range(180):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, 8, 8, 57))
        PredictedBatchData = session.run(y_pred, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, 4))
       
        PredictedBatchData = PredictedBatchData
        Y_ClassifiedResult_Reshaped = Y_ClassifiedResult_Reshaped
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
            Accuracy = Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
            Accuracy = (Accuracy + (Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]))/(i+1)
            
    print('Accuracy: ', (Accuracy))
    
     #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 0.426993
Step 1000: Minibatch Loss: 0.440908
Step 2000: Minibatch Loss: 0.494485
Step 3000: Minibatch Loss: 0.307295
Step 4000: Minibatch Loss: 0.361861
Step 5000: Minibatch Loss: 0.363509
Step 6000: Minibatch Loss: 0.022574
Step 7000: Minibatch Loss: 0.447135
Step 8000: Minibatch Loss: 0.076906
Step 9000: Minibatch Loss: 0.137674
Step 10000: Minibatch Loss: 0.269812
Step 11000: Minibatch Loss: 0.240500
Step 12000: Minibatch Loss: 0.004962
Step 13000: Minibatch Loss: 0.183443
Step 14000: Minibatch Loss: 0.162092
Step 15000: Minibatch Loss: 0.018750
Step 16000: Minibatch Loss: 0.066964
Step 17000: Minibatch Loss: 0.006753
Step 18000: Minibatch Loss: 0.164363
Step 19000: Minibatch Loss: 0.018963
Step 20000: Minibatch Loss: 0.103038
Step 21000: Minibatch Loss: 0.122517
Step 22000: Minibatch Loss: 0.061924
Step 23000: Minibatch Loss: 0.007964
Step 24000: Minibatch Loss: 0.048877
Step 25000: Minibatch Loss: 0.007450
Step 26000: Minibatch Loss: 0.023260
Step 27000: Mi

48
Result of predicting EntireData
[[  9.90602374e-01   1.21160317e-02   2.03914940e-04   9.94910955e-01]
 [  9.68614101e-01  -5.77402115e-03   8.76727700e-03   9.70128059e-01]
 [  9.99294162e-01   1.96946580e-02  -2.46465206e-03   1.00250101e+00]
 [  9.86802340e-01   1.01496894e-02   3.42214853e-03   9.86585617e-01]
 [  1.00622976e+00   2.43192185e-02  -1.93506479e-03   1.01148832e+00]
 [  1.01311874e+00   3.09540499e-02  -2.05433369e-03   1.01325274e+00]
 [  9.59428191e-01  -1.40638351e-02   1.29476637e-02   9.61541057e-01]
 [  1.00737429e+00   2.61522699e-02  -2.48599052e-03   1.01048911e+00]
 [  9.97278333e-01   1.84174050e-02  -1.14917755e-03   1.00081551e+00]
 [  1.00305104e+00   2.22996194e-02  -4.51445580e-04   1.00606656e+00]]
49
Result of predicting EntireData
[[  9.99262929e-01   1.98735166e-02   1.71303749e-04   9.99396801e-01]
 [  9.69776750e-01  -5.19573689e-03   7.07843900e-03   9.72598314e-01]
 [  9.84858871e-01   8.52313824e-03   2.68068910e-03   9.84944880e-01]
 [  1.

99
Result of predicting EntireData
[[ 2.09080625  1.02240884  2.05932236  1.00604355]
 [ 2.04979038  0.97458518  1.9792397   0.94627047]
 [ 2.03054667  0.99661529  1.96992743  0.95747125]
 [ 2.00859499  1.07501423  1.95323431  1.00350106]
 [ 1.99557066  0.97085083  1.98780203  0.98410916]
 [ 2.00396752  0.98186934  2.05576253  1.02647734]
 [ 2.03979254  0.88933665  2.02014852  0.92150915]
 [ 2.03760648  1.06440246  1.98733294  1.04112279]
 [ 2.03084636  0.99988508  2.00610948  1.01661777]
 [ 1.97638988  0.91777313  2.05206418  0.99802756]]
100
Result of predicting EntireData
[[ 0.97400737  0.02497404  1.04433167 -0.02082646]
 [ 0.99797642  0.05095981  1.00804877 -0.06374151]
 [ 1.03448355  0.09561567  1.02914131 -0.03039557]
 [ 0.97847259 -0.01390368  0.99125868 -0.02585053]
 [ 0.95412683 -0.0118795   1.02878153  0.00533287]
 [ 0.95818245 -0.02512097  1.06206906 -0.01637232]
 [ 0.94625556 -0.02310359  1.036026    0.0021715 ]
 [ 1.04603529  0.05288427  0.99512976 -0.00998539]
 [ 0.97822

152
Result of predicting EntireData
[[-0.01715803  1.99109745  0.98494774  0.92813027]
 [-0.06709582  2.0473094   0.92512113  0.91376084]
 [-0.02693981  1.91783035  1.0397054   0.91377151]
 [-0.05752826  1.96802068  0.98652929  0.89009094]
 [ 0.00607279  2.00046492  0.94147259  0.90251416]
 [-0.04281574  1.96065986  1.05362141  0.95006353]
 [-0.03808719  2.06095767  0.97485012  0.99380797]
 [ 0.03301725  2.03299665  0.97655362  0.97395641]
 [ 0.03301725  2.03299665  0.97655362  0.97395641]
 [-0.10605782  1.98786461  0.93992555  0.94100851]]
153
Result of predicting EntireData
[[ 0.04251871  1.98473179  1.04615831  0.98851097]
 [ 0.04251871  1.98473179  1.04615831  0.98851097]
 [ 0.07782826  1.92604625  1.04727101  0.96636766]
 [ 0.02902862  2.08277678  0.93676162  1.05155647]
 [ 0.1079239   1.98183429  1.01747513  0.93595093]
 [-0.02553767  2.04369831  0.96545821  0.9627738 ]
 [-0.02553767  2.04369831  0.96545821  0.9627738 ]
 [-0.06540626  1.96354091  1.03541672  0.99528015]
 [ 0.0599

Result of Test Data
0 0 1 1
[[ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 

Result of Test Data
2 2 1 1
[[ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 