In [1]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
import random

os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [2]:
#Power Pressure Gas1 Gas2
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
data = pd.read_excel('12th.xlsx') # LMML
data = data.values
RealOESdata = data[151:251,1:]
data = pd.read_excel('14th.xlsx') # MLHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('16th.xlsx') # HMML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('17th.xlsx') # LMLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('21th.xlsx') # HMHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('23th.xlsx') # MLML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('24th.xlsx') # HMLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('25th.xlsx') # LMMH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
####
data = pd.read_excel('1st.xlsx') # MMHH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('7th.xlsx') # MMLH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('15th.xlsx') # LHMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('22th.xlsx') # MHLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('26th.xlsx') # MMMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))



In [3]:
Y_ClassifiedResult = np.array([0, 1, 1, 0])
#for k in range(99):
#    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 1, 2])))
#for k in range(100):
#    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 2, 1])))
#for k in range(100):
#    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 2])))
#for k in range(100):
#    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 1])))
#for k in range(100):
#    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 0, 1])))
for k in range(99):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 1, 2])))
##############################################
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 2, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 0, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 2, 1, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 2, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 1, 1])))
    
Sequence = np.array([0])
for k in range(129):
    Sequence = np.hstack((Sequence, np.array([k+1])))

Sequence
#Y_ClassifiedResult = np.array([[1, 0, 1, 2],
#                            [0, 1, 2, 1],
#                            [2, 1, 1, 2],
#                            [2, 1, 1, 1],
#                            [1, 0, 0, 1],
#                            [0, 1, 1, 0],
#                            [1, 0, 2, 1],
#                            [2, 1, 1, 0],
#                            [0, 1, 0, 1],
#                            [2, 1, 2, 1],
#                            [1, 0, 1, 0],
#                            [2, 1, 0, 1],
#                            [0, 1, 1, 2]])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

# 1st

In [4]:
learning_rate = 0.00005
tf.set_random_seed(777)
batchsize = 10

def build_CNN_classifier(X):
    
    W_conv1 = tf.Variable(tf.truncated_normal(shape=[1, 1, 57, 57], stddev=0.01)) #filter
    # 1 * 1 * image depth * filter 2개
    b_conv1 = tf.Variable(tf.constant(0.1, shape=[57])) #bias
    # convolution filter 갯수에 맞춤 = 2개
    h_conv1 = tf.nn.elu(tf.nn.conv2d(X, W_conv1, strides=[1, 1, 1, 1], padding='VALID') + b_conv1)
    print(h_conv1)
    # convolution 연산 수행. 
    # stride >> 2칸씩 움직이는게 목표라면 [1, 2, 2, 1]로 수정
    # padding >> 'SAME' 이면 stride에 맞추어 최소 size의 padding으로 convolution
    #            'VALID' 이면 stride에 맞추어 계산 가능한 만큼만 계산. 나머지 계산 안된건 버림
    
  # 첫번째 Pooling layer
  #h_pool1 = tf.nn.max_pool(h_conv1, ksize=[1, 3, 3, 1], strides=[1, 2, 2, 1], padding='SAME')
    # 3*3 필터를 2의 stride를 가지고 움직임
    # max pooling

  # 2nd : 8*8*57 -> 5*5*57*114(filter) -> 4*4*114
    W_conv2 = tf.Variable(tf.truncated_normal(shape=[5, 5, 57, 114], stddev=0.01))
    b_conv2 = tf.Variable(tf.constant(0.1, shape=[114]))
    h_conv2 = tf.nn.elu(tf.nn.conv2d(h_conv1, W_conv2, strides=[1, 1, 1, 1], padding='VALID') + b_conv2)
    print(h_conv2)

  # 3rd : 4*4*114 -> 3*3*114*38(filter) -> 2*2*38
    W_conv3 = tf.Variable(tf.truncated_normal(shape=[3, 3, 114, 38], stddev=0.01))
    b_conv3 = tf.Variable(tf.constant(0.1, shape=[38]))
    h_conv3 = tf.nn.elu(tf.nn.conv2d(h_conv2, W_conv3, strides=[1, 1, 1, 1], padding='VALID') + b_conv3)
    print(h_conv3)

  # 2*2*38 -> 8개의 neuron으로 (FCNN)
    W_fc1 = tf.Variable(tf.truncated_normal(shape=[2*2*38, 8], stddev=0.01))
    b_fc1 = tf.Variable(tf.constant(0.1, shape=[8]))
    h_conv4_flat = tf.reshape(h_conv3, [-1, 2*2*38])
    h_fc1 = tf.nn.elu(tf.matmul(h_conv4_flat, W_fc1) + b_fc1)
    print(h_fc1)
    
  # 8 -> 4
    W_fc2 = tf.Variable(tf.truncated_normal(shape=[8, 4], stddev=0.01))
    b_fc2 = tf.Variable(tf.constant(0.1, shape=[4]))
    y_pred = tf.nn.elu(tf.matmul(h_fc1,W_fc2) + b_fc2)
    print(y_pred)

    return y_pred

X = tf.placeholder(tf.float32, shape=[None, 8, 8, 57])
Y = tf.placeholder(tf.float32, shape=[None, 4])

y_pred = build_CNN_classifier(X)

cost = tf.reduce_mean(tf.pow(Y - y_pred, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate, beta1 = 0.5).minimize(cost)

Accuracy = y_pred

Tensor("Elu:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("Elu_1:0", shape=(?, 4, 4, 114), dtype=float32)
Tensor("Elu_2:0", shape=(?, 2, 2, 38), dtype=float32)
Tensor("Elu_3:0", shape=(?, 8), dtype=float32)
Tensor("Elu_4:0", shape=(?, 4), dtype=float32)


In [5]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range (100001):
        Order = Sequence[step % 130]
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 8, 8, 57))
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 4))
        
        _, MinibatchCost = session.run([train, cost], feed_dict = {X: batch_X, Y: batch_Y})
        
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchCost))
            
        if step % 130 == 0:
            random.shuffle(Sequence)
    
    for i in range(130):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, 8, 8, 57))
        PredictedBatchData = session.run(y_pred, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, 4))
       
        PredictedBatchData = PredictedBatchData
        Y_ClassifiedResult_Reshaped = Y_ClassifiedResult_Reshaped
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
            Accuracy = Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
            Accuracy = (Accuracy + (Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]))/(i+1)
            
    print('Accuracy: ', (Accuracy))
    
     #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    
    ##########################
    #-------------------------------------------#
    data2 = pd.read_excel('2nd.xlsx') # MLMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('4th.xlsx') # LMHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 1 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('6th.xlsx') # HMMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('8th.xlsx') # HMMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('10th.xlsx') # MLLM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 0 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 0.423853
Step 1000: Minibatch Loss: 0.022898
Step 2000: Minibatch Loss: 0.499894
Step 3000: Minibatch Loss: 0.488782
Step 4000: Minibatch Loss: 0.391745
Step 5000: Minibatch Loss: 0.411975
Step 6000: Minibatch Loss: 0.409084
Step 7000: Minibatch Loss: 0.608508
Step 8000: Minibatch Loss: 0.604343
Step 9000: Minibatch Loss: 0.401824
Step 10000: Minibatch Loss: 0.556442
Step 11000: Minibatch Loss: 0.454957
Step 12000: Minibatch Loss: 0.511460
Step 13000: Minibatch Loss: 0.569821
Step 14000: Minibatch Loss: 0.542047
Step 15000: Minibatch Loss: 0.189452
Step 16000: Minibatch Loss: 0.383844
Step 17000: Minibatch Loss: 0.499229
Step 18000: Minibatch Loss: 0.186650
Step 19000: Minibatch Loss: 0.368785
Step 20000: Minibatch Loss: 0.483841
Step 21000: Minibatch Loss: 0.189031
Step 22000: Minibatch Loss: 0.519632
Step 23000: Minibatch Loss: 0.577494
Step 24000: Minibatch Loss: 0.519293
Step 25000: Minibatch Loss: 0.552558
Step 26000: Minibatch Loss: 0.244601
Step 27000: Mi

42
Result of predicting EntireData
[[ 1.97379124  1.21877456  1.93641591  1.04326308]
 [ 1.97379124  1.21877456  1.93641591  1.04326308]
 [ 1.9618119   1.11838651  1.99150753  1.04390442]
 [ 1.99298608  1.15451133  2.02165794  1.04215419]
 [ 1.99527085  1.13955402  2.05235791  1.01699591]
 [ 2.05092859  1.11692083  2.05452585  1.0272634 ]
 [ 2.057868    1.13434231  2.04520416  1.0244211 ]
 [ 2.03464723  1.17475367  2.03014326  1.04582858]
 [ 2.13490558  1.08892787  2.09051728  1.04186177]
 [ 2.03391933  1.14482546  2.03486681  1.04100287]]
43
Result of predicting EntireData
[[ 2.03391933  1.14482546  2.03486681  1.04100287]
 [ 2.09073067  1.0901227   2.06389165  1.01199734]
 [ 1.98743856  1.1411078   2.01642036  1.0140692 ]
 [ 2.0455792   0.9999001   2.08122873  1.02920997]
 [ 2.08754325  1.09220684  2.05244374  1.02962124]
 [ 1.98129499  1.13101006  2.02500844  0.97294074]
 [ 2.09198117  1.05012894  2.06127095  1.01178026]
 [ 2.09198117  1.05012894  2.06127095  1.01178026]
 [ 2.079850

94
Result of predicting EntireData
[[ 0.95841253  0.98769999  0.05629835  1.97602618]
 [ 0.95966423  0.9699412   0.09474286  2.00600266]
 [ 1.01490843  0.96426141  0.09420332  1.98754144]
 [ 0.95253432  0.99032056  0.06723079  2.0022738 ]
 [ 0.97270238  0.96805483  0.11673674  2.04182243]
 [ 0.95990455  0.96575099  0.09784397  2.00685239]
 [ 0.98954082  0.94489115  0.14893827  1.9937824 ]
 [ 0.96314454  0.98602766  0.11983117  2.01996922]
 [ 0.96750212  0.98142976  0.10721335  1.98187065]
 [ 0.94416595  0.97456568  0.0863646   2.01007628]]
95
Result of predicting EntireData
[[ 0.99062109  0.96546406  0.10838255  1.98516881]
 [ 0.96499753  0.96036124  0.10807547  2.00684524]
 [ 0.96293283  0.99326104  0.09664068  2.00705385]
 [ 0.97016442  0.94728029  0.13792667  2.01982236]
 [ 0.97163475  0.99351078  0.1159142   2.01167321]
 [ 0.97495461  0.98123306  0.11136326  2.02093601]
 [ 0.98747385  0.96099997  0.1256071   2.01622009]
 [ 0.97223294  0.99474353  0.1162158   2.01542735]
 [ 0.981854

Result of Test Data
0 0 1 1
[[ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  2.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  2.  1.]
 [ 1.  0.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  2.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
2 2 1 1
[[ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  2.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 

Result of Test Data
1 2 1 2
[[ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 1.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 1.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 

Result of Test Data
0 1 2 1
[[ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 

Result of Test Data
2 1 1 1
[[ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 2.  1.  1.  1.]
 [ 

# 2nd

In [6]:
learning_rate = 0.0001
tf.set_random_seed(777)
batchsize = 10

def build_CNN_classifier(X):
    
    W_conv1 = tf.Variable(tf.truncated_normal(shape=[1, 1, 57, 57], stddev=0.01)) #filter
    # 1 * 1 * image depth * filter 2개
    b_conv1 = tf.Variable(tf.constant(0.1, shape=[57])) #bias
    # convolution filter 갯수에 맞춤 = 2개
    h_conv1 = tf.nn.elu(tf.nn.conv2d(X, W_conv1, strides=[1, 1, 1, 1], padding='VALID') + b_conv1)
    print(h_conv1)
    # convolution 연산 수행. 
    # stride >> 2칸씩 움직이는게 목표라면 [1, 2, 2, 1]로 수정
    # padding >> 'SAME' 이면 stride에 맞추어 최소 size의 padding으로 convolution
    #            'VALID' 이면 stride에 맞추어 계산 가능한 만큼만 계산. 나머지 계산 안된건 버림
    
  # 첫번째 Pooling layer
  #h_pool1 = tf.nn.max_pool(h_conv1, ksize=[1, 3, 3, 1], strides=[1, 2, 2, 1], padding='SAME')
    # 3*3 필터를 2의 stride를 가지고 움직임
    # max pooling

  # 2nd : 8*8*57 -> 5*5*57*114(filter) -> 4*4*114
    W_conv2 = tf.Variable(tf.truncated_normal(shape=[5, 5, 57, 114], stddev=0.01))
    b_conv2 = tf.Variable(tf.constant(0.1, shape=[114]))
    h_conv2 = tf.nn.elu(tf.nn.conv2d(h_conv1, W_conv2, strides=[1, 1, 1, 1], padding='VALID') + b_conv2)
    print(h_conv2)

  # 3rd : 4*4*114 -> 3*3*114*38(filter) -> 2*2*38
    W_conv3 = tf.Variable(tf.truncated_normal(shape=[3, 3, 114, 38], stddev=0.01))
    b_conv3 = tf.Variable(tf.constant(0.1, shape=[38]))
    h_conv3 = tf.nn.elu(tf.nn.conv2d(h_conv2, W_conv3, strides=[1, 1, 1, 1], padding='VALID') + b_conv3)
    print(h_conv3)

  # 2*2*38 -> 8개의 neuron으로 (FCNN)
    W_fc1 = tf.Variable(tf.truncated_normal(shape=[2*2*38, 8], stddev=0.01))
    b_fc1 = tf.Variable(tf.constant(0.1, shape=[8]))
    h_conv4_flat = tf.reshape(h_conv3, [-1, 2*2*38])
    h_fc1 = tf.nn.elu(tf.matmul(h_conv4_flat, W_fc1) + b_fc1)
    print(h_fc1)
    
  # 8 -> 4
    W_fc2 = tf.Variable(tf.truncated_normal(shape=[8, 4], stddev=0.01))
    b_fc2 = tf.Variable(tf.constant(0.1, shape=[4]))
    y_pred = tf.nn.elu(tf.matmul(h_fc1,W_fc2) + b_fc2)
    print(y_pred)

    return y_pred

X = tf.placeholder(tf.float32, shape=[None, 8, 8, 57])
Y = tf.placeholder(tf.float32, shape=[None, 4])

y_pred = build_CNN_classifier(X)

cost = tf.reduce_mean(tf.pow(Y - y_pred, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

Accuracy = y_pred

Tensor("Elu_5:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("Elu_6:0", shape=(?, 4, 4, 114), dtype=float32)
Tensor("Elu_7:0", shape=(?, 2, 2, 38), dtype=float32)
Tensor("Elu_8:0", shape=(?, 8), dtype=float32)
Tensor("Elu_9:0", shape=(?, 4), dtype=float32)


In [7]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range (200001):
        Order = Sequence[step % 130]
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 8, 8, 57))
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 4))
        
        _, MinibatchCost = session.run([train, cost], feed_dict = {X: batch_X, Y: batch_Y})
        
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchCost))
            
        if step % 130 == 0:
            random.shuffle(Sequence)
    
    for i in range(130):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, 8, 8, 57))
        PredictedBatchData = session.run(y_pred, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, 4))
       
        PredictedBatchData = PredictedBatchData
        Y_ClassifiedResult_Reshaped = Y_ClassifiedResult_Reshaped
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
            Accuracy = Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
            Accuracy = (Accuracy + (Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]))/(i+1)
            
    print('Accuracy: ', (Accuracy))
    
     #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    
    ##########################
    #-------------------------------------------#
    data2 = pd.read_excel('2nd.xlsx') # MLMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('4th.xlsx') # LMHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 1 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('6th.xlsx') # HMMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('8th.xlsx') # HMMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('10th.xlsx') # MLLM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 0 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 0.445461
Step 1000: Minibatch Loss: 0.406486
Step 2000: Minibatch Loss: 0.565820
Step 3000: Minibatch Loss: 0.784007
Step 4000: Minibatch Loss: 0.395572
Step 5000: Minibatch Loss: 0.317764
Step 6000: Minibatch Loss: 0.263700
Step 7000: Minibatch Loss: 0.546712
Step 8000: Minibatch Loss: 0.549821
Step 9000: Minibatch Loss: 0.315112
Step 10000: Minibatch Loss: 0.196594
Step 11000: Minibatch Loss: 0.281074
Step 12000: Minibatch Loss: 0.008848
Step 13000: Minibatch Loss: 0.281037
Step 14000: Minibatch Loss: 0.348466
Step 15000: Minibatch Loss: 0.107149
Step 16000: Minibatch Loss: 0.540833
Step 17000: Minibatch Loss: 0.254152
Step 18000: Minibatch Loss: 0.111369
Step 19000: Minibatch Loss: 0.436754
Step 20000: Minibatch Loss: 0.340988
Step 21000: Minibatch Loss: 0.129946
Step 22000: Minibatch Loss: 0.006360
Step 23000: Minibatch Loss: 0.392978
Step 24000: Minibatch Loss: 0.437246
Step 25000: Minibatch Loss: 0.138865
Step 26000: Minibatch Loss: 0.314411
Step 27000: Mi

44
Result of predicting EntireData
[[ 2.0202086   0.9940784   1.98211062  0.9602862 ]
 [ 2.0202086   0.9940784   1.98211062  0.9602862 ]
 [ 1.99674845  0.98797745  1.97797406  0.97388417]
 [ 2.00977468  1.00640225  1.97880864  0.96832174]
 [ 2.00977468  1.00640225  1.97880864  0.96832174]
 [ 1.95661783  1.02242374  1.96239102  0.9557991 ]
 [ 2.00683165  1.00101614  1.9912051   0.98279643]
 [ 2.00474334  1.00019884  1.97328162  0.96730173]
 [ 2.01827025  1.00701118  1.98177648  0.9793613 ]
 [ 1.93394399  1.05742943  1.9417938   0.99732041]]
45
Result of predicting EntireData
[[ 2.02322817  0.99386257  1.97436452  0.94272912]
 [ 2.02322817  0.99386257  1.97436452  0.94272912]
 [ 2.01345778  0.9889043   1.97842586  0.95882088]
 [ 2.01345778  0.9889043   1.97842586  0.95882088]
 [ 2.00689197  0.9962582   1.99062192  0.98320925]
 [ 2.01112485  1.00116706  1.96977997  0.95534742]
 [ 2.01112485  1.00116706  1.96977997  0.95534742]
 [ 2.00657296  1.00985205  1.95000505  0.93972731]
 [ 1.998447

 [ 1.  1. -0.  2.]]
Original Data
[1 1 0 2]
91
Result of predicting EntireData
[[  9.93376613e-01   9.87259507e-01  -3.29548120e-02   1.98374569e+00]
 [  9.96102333e-01   9.84753609e-01  -5.91152906e-03   1.95529366e+00]
 [  9.96183455e-01   9.83648002e-01  -5.04248142e-02   1.97858310e+00]
 [  9.95129466e-01   9.85850811e-01  -3.30214500e-02   1.97489643e+00]
 [  9.95857716e-01   9.83751118e-01   7.19457865e-04   1.95567060e+00]
 [  9.95770037e-01   9.86813486e-01  -2.64211297e-02   1.96514714e+00]
 [  9.92630184e-01   9.93048608e-01  -4.37571406e-02   1.98292625e+00]
 [  9.93911862e-01   9.90657866e-01  -7.98350573e-03   1.95454657e+00]
 [  9.95243430e-01   9.89591837e-01  -1.38542652e-02   1.95212770e+00]
 [  9.93048668e-01   9.85096574e-01  -5.12729287e-02   1.99512470e+00]]
92
Result of predicting EntireData
[[ 0.99025744  0.99091518 -0.0853765   2.01486516]
 [ 0.99322438  0.98851007 -0.05352896  1.99121404]
 [ 0.99712396  0.98562264 -0.05741698  1.97309923]
 [ 0.99358594  0.98759

Result of Test Data
0 0 1 1
[[ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  2.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 0. -0.  1.  1.]
 [ 

Result of Test Data
2 2 1 1
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [-0.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 

Result of Test Data
1 2 1 2
[[ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  0.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  0.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 0.  1.  1.  2.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  0.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 

Result of Test Data
0 1 2 1
[[ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 

Result of Test Data
2 1 1 1
[[ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 1.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 2.  0.  1.  0.]
 [ 

# 3rd

In [8]:
learning_rate = 0.0001
tf.set_random_seed(777)
batchsize = 10

def build_CNN_classifier(X):
    
    W_conv1 = tf.Variable(tf.truncated_normal(shape=[1, 1, 57, 57], stddev=0.01)) #filter
    # 1 * 1 * image depth * filter 2개
    b_conv1 = tf.Variable(tf.constant(0.1, shape=[57])) #bias
    # convolution filter 갯수에 맞춤 = 2개
    h_conv1 = tf.nn.elu(tf.nn.conv2d(X, W_conv1, strides=[1, 1, 1, 1], padding='VALID') + b_conv1)
    print(h_conv1)
    # convolution 연산 수행. 
    # stride >> 2칸씩 움직이는게 목표라면 [1, 2, 2, 1]로 수정
    # padding >> 'SAME' 이면 stride에 맞추어 최소 size의 padding으로 convolution
    #            'VALID' 이면 stride에 맞추어 계산 가능한 만큼만 계산. 나머지 계산 안된건 버림
    
  # 첫번째 Pooling layer
  #h_pool1 = tf.nn.max_pool(h_conv1, ksize=[1, 3, 3, 1], strides=[1, 2, 2, 1], padding='SAME')
    # 3*3 필터를 2의 stride를 가지고 움직임
    # max pooling

  # 2nd : 8*8*57 -> 5*5*57*114(filter) -> 4*4*57
    W_conv2 = tf.Variable(tf.truncated_normal(shape=[5, 5, 57, 57], stddev=0.01))
    b_conv2 = tf.Variable(tf.constant(0.1, shape=[57]))
    h_conv2 = tf.nn.elu(tf.nn.conv2d(h_conv1, W_conv2, strides=[1, 1, 1, 1], padding='VALID') + b_conv2)
    print(h_conv2)

  # 3rd : 4*4*57 -> 3*3*57*19(filter) -> 2*2*19
    W_conv3 = tf.Variable(tf.truncated_normal(shape=[3, 3, 57, 19], stddev=0.01))
    b_conv3 = tf.Variable(tf.constant(0.1, shape=[19]))
    h_conv3 = tf.nn.elu(tf.nn.conv2d(h_conv2, W_conv3, strides=[1, 1, 1, 1], padding='VALID') + b_conv3)
    print(h_conv3)

  # 2*2*38 -> 8개의 neuron으로 (FCNN)
    W_fc1 = tf.Variable(tf.truncated_normal(shape=[2*2*19, 8], stddev=0.01))
    b_fc1 = tf.Variable(tf.constant(0.1, shape=[8]))
    h_conv4_flat = tf.reshape(h_conv3, [-1, 2*2*19])
    h_fc1 = tf.nn.elu(tf.matmul(h_conv4_flat, W_fc1) + b_fc1)
    print(h_fc1)
    
  # 8 -> 4
    W_fc2 = tf.Variable(tf.truncated_normal(shape=[8, 4], stddev=0.01))
    b_fc2 = tf.Variable(tf.constant(0.1, shape=[4]))
    y_pred = tf.nn.elu(tf.matmul(h_fc1,W_fc2) + b_fc2)
    print(y_pred)

    return y_pred

X = tf.placeholder(tf.float32, shape=[None, 8, 8, 57])
Y = tf.placeholder(tf.float32, shape=[None, 4])

y_pred = build_CNN_classifier(X)

cost = tf.reduce_mean(tf.pow(Y - y_pred, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

Accuracy = y_pred

Tensor("Elu_10:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("Elu_11:0", shape=(?, 4, 4, 57), dtype=float32)
Tensor("Elu_12:0", shape=(?, 2, 2, 19), dtype=float32)
Tensor("Elu_13:0", shape=(?, 8), dtype=float32)
Tensor("Elu_14:0", shape=(?, 4), dtype=float32)


In [9]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range (200001):
        Order = Sequence[step % 130]
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 8, 8, 57))
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 4))
        
        _, MinibatchCost = session.run([train, cost], feed_dict = {X: batch_X, Y: batch_Y})
        
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchCost))
            
        if step % 130 == 0:
            random.shuffle(Sequence)
    
    for i in range(130):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, 8, 8, 57))
        PredictedBatchData = session.run(y_pred, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, 4))
       
        PredictedBatchData = PredictedBatchData
        Y_ClassifiedResult_Reshaped = Y_ClassifiedResult_Reshaped
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
            Accuracy = Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
            Accuracy = (Accuracy + (Y_ClassifiedResult_Reshaped - Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:]))/(i+1)
            
    print('Accuracy: ', (Accuracy))
    
     #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    
    ##########################
    #-------------------------------------------#
    data2 = pd.read_excel('2nd.xlsx') # MLMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('4th.xlsx') # LMHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 1 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('6th.xlsx') # HMMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('8th.xlsx') # HMMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('10th.xlsx') # MLLM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 0 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 1.308401
Step 1000: Minibatch Loss: 0.494261
Step 2000: Minibatch Loss: 0.654807
Step 3000: Minibatch Loss: 0.298330
Step 4000: Minibatch Loss: 0.113726
Step 5000: Minibatch Loss: 0.349177
Step 6000: Minibatch Loss: 0.095366
Step 7000: Minibatch Loss: 0.222779
Step 8000: Minibatch Loss: 0.257552
Step 9000: Minibatch Loss: 0.260547
Step 10000: Minibatch Loss: 0.466312
Step 11000: Minibatch Loss: 0.103922
Step 12000: Minibatch Loss: 0.191537
Step 13000: Minibatch Loss: 0.023884
Step 14000: Minibatch Loss: 0.071835
Step 15000: Minibatch Loss: 0.367171
Step 16000: Minibatch Loss: 0.109875
Step 17000: Minibatch Loss: 0.047681
Step 18000: Minibatch Loss: 0.256686
Step 19000: Minibatch Loss: 0.030675
Step 20000: Minibatch Loss: 0.222977
Step 21000: Minibatch Loss: 0.015861
Step 22000: Minibatch Loss: 0.123309
Step 23000: Minibatch Loss: 0.028566
Step 24000: Minibatch Loss: 0.091249
Step 25000: Minibatch Loss: 0.105268
Step 26000: Minibatch Loss: 0.221683
Step 27000: Mi

 [ 2.02399206  0.97980666  2.01263618  1.00916445]]
42
Result of predicting EntireData
[[ 2.0366714   0.99697018  2.00180864  1.00177932]
 [ 2.0366714   0.99697018  2.00180864  1.00177932]
 [ 2.02243519  1.00805771  2.0096128   1.01100886]
 [ 2.03507185  1.00134492  2.00008893  1.00080752]
 [ 2.01921082  1.00829995  1.99718261  0.99909937]
 [ 2.03070235  0.99593699  2.02136016  1.02049744]
 [ 2.03961825  1.00176919  2.01412559  1.01422775]
 [ 2.01669431  1.00064659  1.99971437  1.00065613]
 [ 2.06367946  0.98492837  2.02519202  1.02216482]
 [ 2.0176363   1.00850499  1.9834311   0.98726368]]
43
Result of predicting EntireData
[[ 2.0176363   1.00850499  1.9834311   0.98726368]
 [ 2.04405689  1.0106014   1.98837805  0.99141288]
 [ 2.01848888  1.01456404  1.99508119  0.99810731]
 [ 2.04791379  0.99180377  2.03240228  1.03072846]
 [ 2.01891232  0.99479353  1.98357081  0.9852972 ]
 [ 2.00383019  1.00842786  1.99807954  1.00053906]
 [ 2.0167892   1.00934064  1.99741387  1.00023687]
 [ 2.01678

81
Result of predicting EntireData
[[ 1.01726592  0.97526813  1.99319601  2.00246334]
 [ 1.01118493  0.98435467  1.99870658  2.00565982]
 [ 1.01909482  0.97753376  2.00331402  2.02049279]
 [ 1.00912595  0.98502845  1.98561192  1.97919238]
 [ 1.00762773  0.99386948  1.99248004  1.98508751]
 [ 1.02632141  0.97711301  2.00558949  2.02509284]
 [ 1.00052416  1.00629699  1.99590158  1.98118746]
 [ 0.99442607  1.01377511  1.99301243  1.9689846 ]
 [ 0.99977744  0.99723339  1.98296666  1.96359921]
 [ 1.00611305  0.98817986  1.98556089  1.97638428]]
82
Result of predicting EntireData
[[ 1.01558471  0.98972112  2.00342774  2.01023102]
 [ 1.00829399  0.99515396  1.99327564  1.985587  ]
 [ 1.00708663  0.99066681  1.99712658  1.99718094]
 [ 1.00447035  0.99718904  1.98955059  1.97642696]
 [ 0.99832898  1.00739515  1.98939371  1.9673233 ]
 [ 1.00580931  1.00104094  1.99312973  1.98012984]
 [ 1.00382221  0.9935385   1.99808168  1.99667752]
 [ 1.00334895  1.00003731  1.98200607  1.95908391]
 [ 1.006281

 [ 1.01746821  0.92560917  1.03494239  0.9908666 ]]
129
Result of predicting EntireData
[[ 1.01311159  0.98355275  1.01459813  1.00034881]
 [ 1.01836622  0.98023283  1.01104331  1.00229323]
 [ 1.01508212  1.0196346   1.00618911  1.0116663 ]
 [ 1.00424683  1.00011289  0.99766749  1.00693154]
 [ 1.00542796  0.98864508  1.02510583  1.00444758]
 [ 1.02021968  1.01761985  0.98316771  1.01044774]
 [ 1.01984286  0.99044049  1.0048058   1.01105559]
 [ 1.01569724  1.00207591  0.9676972   1.00277555]
 [ 0.99826974  1.00440204  1.00520468  1.00024331]
 [ 1.01121628  0.97096413  0.99896723  0.97875291]]
Accuracy:  [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Result of Test Data
0 0 1 1
[[ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]


Result of Test Data
2 2 1 1
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 0.  1.  1. -0.]
 [ 

Result of Test Data
1 2 1 2
[[ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 

Result of Test Data
0 1 2 1
[[ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [ 

Result of Test Data
2 1 1 2
[[ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 

Result of Test Data
1 0 0 1
[[ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 2.  1. -0.  1.]
 [ 

# 4th

In [11]:
learning_rate = 0.0001
tf.set_random_seed(777)
batchsize = 10

def build_CNN_classifier(X):
    
    W_conv1 = tf.Variable(tf.truncated_normal(shape=[1, 1, 57, 57], stddev=0.01)) #filter
    # 1 * 1 * image depth * filter 57개
    b_conv1 = tf.Variable(tf.constant(0.1, shape=[57])) #bias
    # convolution filter 갯수에 맞춤 = 2개
    h_conv1 = tf.nn.elu(tf.nn.conv2d(X, W_conv1, strides=[1, 1, 1, 1], padding='VALID') + b_conv1)
    
    print(h_conv1)
    # convolution 연산 수행. 
    # stride >> 2칸씩 움직이는게 목표라면 [1, 2, 2, 1]로 수정
    # padding >> 'SAME' input image의 크기와 똑같이 계산
    #            'VALID' 이면 stride에 맞추어 계산 가능한 만큼만 계산. 나머지 계산 안된건 버림
    
  # 첫번째 Pooling layer
  #h_pool1 = tf.nn.max_pool(h_conv1, ksize=[1, 3, 3, 1], strides=[1, 2, 2, 1], padding='SAME')
    # 3*3 필터를 2의 stride를 가지고 움직임
    # max pooling

  # 2nd : 8*8*57 -> 3*3*57*57(filter) -> 8*8*57 -> 4*4*57
    W_conv2 = tf.Variable(tf.truncated_normal(shape=[3, 3, 57, 57], stddev=0.01))
    b_conv2 = tf.Variable(tf.constant(0.1, shape=[57]))
    h_conv2 = tf.nn.elu(tf.nn.conv2d(h_conv1, W_conv2, strides=[1, 1, 1, 1], padding='SAME') + b_conv2)
    h_pool1 = tf.nn.max_pool(h_conv2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='VALID')
    print(h_conv2)
    print(h_pool1)
    
  # 3rd : 4*4*57 -> 3*3*57*19(filter) -> 4*4*19 -> 2*2*19
    W_conv3 = tf.Variable(tf.truncated_normal(shape=[3, 3, 57, 19], stddev=0.01))
    b_conv3 = tf.Variable(tf.constant(0.1, shape=[19]))
    h_conv3 = tf.nn.elu(tf.nn.conv2d(h_pool1, W_conv3, strides=[1, 1, 1, 1], padding='SAME') + b_conv3)
    h_pool2 = tf.nn.max_pool(h_conv3, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='VALID')
    print(h_conv3)
    print(h_pool2)

  # 2*2*38 -> 8개의 neuron으로 (FCNN)
    W_fc1 = tf.Variable(tf.truncated_normal(shape=[2*2*19, 8], stddev=0.01))
    b_fc1 = tf.Variable(tf.constant(0.1, shape=[8]))
    h_conv4_flat = tf.reshape(h_pool2, [-1, 2*2*19])
    h_fc1 = tf.nn.elu(tf.matmul(h_conv4_flat, W_fc1) + b_fc1)
    print(h_fc1)
    
  # 8 -> 4
    W_fc2 = tf.Variable(tf.truncated_normal(shape=[8, 4], stddev=0.01))
    b_fc2 = tf.Variable(tf.constant(0.1, shape=[4]))
    y_pred = tf.nn.elu(tf.matmul(h_fc1,W_fc2) + b_fc2)
    print(y_pred)

    return y_pred

X = tf.placeholder(tf.float32, shape=[None, 8, 8, 57])
Y = tf.placeholder(tf.float32, shape=[None, 4])

y_pred = build_CNN_classifier(X)

cost = tf.reduce_mean(tf.pow(Y - y_pred, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

Accuracy = y_pred

Tensor("Elu_20:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("Elu_21:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("MaxPool_2:0", shape=(?, 4, 4, 57), dtype=float32)
Tensor("Elu_22:0", shape=(?, 4, 4, 19), dtype=float32)
Tensor("MaxPool_3:0", shape=(?, 2, 2, 19), dtype=float32)
Tensor("Elu_23:0", shape=(?, 8), dtype=float32)
Tensor("Elu_24:0", shape=(?, 4), dtype=float32)


In [12]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range (100001):
        Order = Sequence[step % 130]
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 8, 8, 57))
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 4))
        
        _, MinibatchCost = session.run([train, cost], feed_dict = {X: batch_X, Y: batch_Y})
        
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchCost))
            
        if step % 130 == 0:
            random.shuffle(Sequence)
    
    for i in range(130):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, 8, 8, 57))
        PredictedBatchData = session.run(y_pred, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, 4))
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
            Accuracy = PredictedBatchData - Y_ClassifiedResult_Reshaped
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
            Accuracy = Accuracy + (PredictedBatchData - Y_ClassifiedResult_Reshaped)
            
    Accuracy = Accuracy / 130
    print('Accuracy: ', (Accuracy))
    
     #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    
    ##########################
    #-------------------------------------------#
    data2 = pd.read_excel('2nd.xlsx') # MLMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('4th.xlsx') # LMHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 1 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('6th.xlsx') # HMMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('8th.xlsx') # HMMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('10th.xlsx') # MLLM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 0 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 0.822097
Step 1000: Minibatch Loss: 0.332294
Step 2000: Minibatch Loss: 0.112190
Step 3000: Minibatch Loss: 0.360247
Step 4000: Minibatch Loss: 0.004848
Step 5000: Minibatch Loss: 0.403004
Step 6000: Minibatch Loss: 0.411863
Step 7000: Minibatch Loss: 0.404103
Step 8000: Minibatch Loss: 0.121300
Step 9000: Minibatch Loss: 0.277390
Step 10000: Minibatch Loss: 0.088926
Step 11000: Minibatch Loss: 0.030905
Step 12000: Minibatch Loss: 0.262156
Step 13000: Minibatch Loss: 0.243661
Step 14000: Minibatch Loss: 0.268818
Step 15000: Minibatch Loss: 0.056413
Step 16000: Minibatch Loss: 0.254169
Step 17000: Minibatch Loss: 0.010262
Step 18000: Minibatch Loss: 0.011900
Step 19000: Minibatch Loss: 0.034069
Step 20000: Minibatch Loss: 0.014606
Step 21000: Minibatch Loss: 0.011175
Step 22000: Minibatch Loss: 0.104853
Step 23000: Minibatch Loss: 0.149137
Step 24000: Minibatch Loss: 0.121789
Step 25000: Minibatch Loss: 0.005680
Step 26000: Minibatch Loss: 0.039115
Step 27000: Mi

45
Result of predicting EntireData
[[ 1.97986472  1.02590382  1.95869112  0.98220736]
 [ 1.97986472  1.02590382  1.95869112  0.98220736]
 [ 1.94334638  1.05150557  1.92288566  0.99458176]
 [ 1.94334638  1.05150557  1.92288566  0.99458176]
 [ 1.98759556  0.99899846  2.00849962  1.00722504]
 [ 1.97592437  1.02885532  1.96505404  0.98791164]
 [ 1.97592437  1.02885532  1.96505404  0.98791164]
 [ 1.9727124   1.00248766  1.99356925  1.0223453 ]
 [ 1.95377576  1.01409507  1.9561578   1.02618814]
 [ 1.95377576  1.01409507  1.9561578   1.02618814]]
46
Result of predicting EntireData
[[ 1.94590056  1.03258383  1.95800424  1.01511669]
 [ 1.96435905  1.00748134  1.9861145   1.02319932]
 [ 2.00763273  1.00389457  2.00132918  0.97722214]
 [ 2.00786829  1.0003438   2.01320338  0.98692286]
 [ 1.94411767  1.02573311  1.96112907  1.02422464]
 [ 1.94919944  1.01601958  1.96763813  1.03060257]
 [ 1.90915895  1.08583009  1.89681363  0.98016942]
 [ 2.01524448  0.99192697  2.02323747  0.98502094]
 [ 1.980073

100
Result of predicting EntireData
[[ -3.12375426e-02   1.99302602e+00   1.00648928e+00   1.03403103e+00]
 [ -2.01894045e-02   2.02535248e+00   1.02355242e+00   1.04333568e+00]
 [ -3.37505341e-02   2.00246239e+00   1.01162863e+00   1.04563487e+00]
 [ -1.52438283e-02   2.00656295e+00   1.00128841e+00   1.03877699e+00]
 [ -4.79341745e-02   2.00499201e+00   1.01641798e+00   1.06472111e+00]
 [ -9.75018740e-03   2.02417636e+00   1.01392150e+00   1.04154325e+00]
 [ -1.51395798e-04   2.00255418e+00   9.80567336e-01   1.03861511e+00]
 [  1.25184655e-03   2.02309847e+00   1.00921905e+00   1.02434289e+00]
 [ -4.22601104e-02   1.99983525e+00   1.00659680e+00   1.06370628e+00]
 [ -1.85599327e-02   1.99476910e+00   9.91430521e-01   1.03620279e+00]]
Result of Rounded off EntireData
[[-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [-0.  2.  1.  1.]
 [-0.  2.  1.  1.]]
Original Data
[0 2 1 1]
101
R

Result of Test Data
0 0 1 1
[[ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 

Result of Test Data
2 2 1 1
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[ 0.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  2.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 

Result of Test Data
1 0 1 2
[[-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [ 0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [-0.  0.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  0.  2.]
 [-0.  0.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  0.  2.]
 [ 

Result of Test Data
2 1 1 2
[[ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  1.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  1.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  1.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  1.  0.  2.]
 [ 0.  1.  0.  2.]
 [ 

Result of Test Data
1 0 0 1
[[ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 2.  1.  0.  1.]
 [ 

# 5th

In [15]:
learning_rate = 0.0001
tf.set_random_seed(777)
batchsize = 10

def build_CNN_classifier(X):
    
    W_conv1 = tf.Variable(tf.truncated_normal(shape=[1, 1, 57, 57], stddev=0.01)) #filter
    # 1 * 1 * image depth * filter 57개
    b_conv1 = tf.Variable(tf.constant(0.1, shape=[57])) #bias
    # convolution filter 갯수에 맞춤 = 2개
    h_conv1 = tf.nn.elu(tf.nn.conv2d(X, W_conv1, strides=[1, 1, 1, 1], padding='VALID') + b_conv1)
    
    print(h_conv1)
    # convolution 연산 수행. 
    # stride >> 2칸씩 움직이는게 목표라면 [1, 2, 2, 1]로 수정
    # padding >> 'SAME' input image의 크기와 똑같이 계산
    #            'VALID' 이면 stride에 맞추어 계산 가능한 만큼만 계산. 나머지 계산 안된건 버림
    
  # 첫번째 Pooling layer
  #h_pool1 = tf.nn.max_pool(h_conv1, ksize=[1, 3, 3, 1], strides=[1, 2, 2, 1], padding='SAME')
    # 3*3 필터를 2의 stride를 가지고 움직임
    # max pooling

  # 2nd : 8*8*57 -> 5*5*57*19(filter) -> 4*4*19 -> 2*2*19
    W_conv2 = tf.Variable(tf.truncated_normal(shape=[5, 5, 57, 19], stddev=0.01))
    b_conv2 = tf.Variable(tf.constant(0.1, shape=[19]))
    h_conv2 = tf.nn.elu(tf.nn.conv2d(h_conv1, W_conv2, strides=[1, 1, 1, 1], padding='VALID') + b_conv2)
    h_pool1 = tf.nn.max_pool(h_conv2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='VALID')
    print(h_conv2)
    print(h_pool1)
    
  # 3rd : 2*2*19 -> 3*3*19*5(filter) -> 2*2*5
    W_conv3 = tf.Variable(tf.truncated_normal(shape=[3, 3, 19, 5], stddev=0.01))
    b_conv3 = tf.Variable(tf.constant(0.1, shape=[5]))
    h_conv3 = tf.nn.elu(tf.nn.conv2d(h_pool1, W_conv3, strides=[1, 1, 1, 1], padding='SAME') + b_conv3)
    print(h_conv3)

  # 2*2*5 -> 8개의 neuron으로 (FCNN)
    W_fc1 = tf.Variable(tf.truncated_normal(shape=[2*2*5, 8], stddev=0.01))
    b_fc1 = tf.Variable(tf.constant(0.1, shape=[8]))
    h_conv4_flat = tf.reshape(h_conv3, [-1, 2*2*5])
    h_fc1 = tf.nn.elu(tf.matmul(h_conv4_flat, W_fc1) + b_fc1)
    print(h_fc1)
    
  # 8 -> 4
    W_fc2 = tf.Variable(tf.truncated_normal(shape=[8, 4], stddev=0.01))
    b_fc2 = tf.Variable(tf.constant(0.1, shape=[4]))
    y_pred = tf.nn.elu(tf.matmul(h_fc1,W_fc2) + b_fc2)
    print(y_pred)

    return y_pred

X = tf.placeholder(tf.float32, shape=[None, 8, 8, 57])
Y = tf.placeholder(tf.float32, shape=[None, 4])

y_pred = build_CNN_classifier(X)

cost = tf.reduce_mean(tf.pow(Y - y_pred, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate, beta1 = 0.5).minimize(cost)

Accuracy = y_pred

Tensor("Elu_32:0", shape=(?, 8, 8, 57), dtype=float32)
Tensor("Elu_33:0", shape=(?, 4, 4, 19), dtype=float32)
Tensor("MaxPool_6:0", shape=(?, 2, 2, 19), dtype=float32)
Tensor("Elu_34:0", shape=(?, 2, 2, 5), dtype=float32)
Tensor("Elu_35:0", shape=(?, 8), dtype=float32)
Tensor("Elu_36:0", shape=(?, 4), dtype=float32)


In [16]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range (100001):
        Order = Sequence[step % 130]
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 8, 8, 57))
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, 4))
        
        _, MinibatchCost = session.run([train, cost], feed_dict = {X: batch_X, Y: batch_Y})
        
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchCost))
            
        if step % 130 == 0:
            random.shuffle(Sequence)
    
    for i in range(130):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, 8, 8, 57))
        PredictedBatchData = session.run(y_pred, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, 4))
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
            Accuracy = np.rint(PredictedBatchData) - Y_ClassifiedResult_Reshaped
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
            Accuracy = Accuracy + (np.rint(PredictedBatchData) - Y_ClassifiedResult_Reshaped)
            
    Accuracy = Accuracy / 130
    print('Accuracy: ', (Accuracy))
    
     #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    
    ##########################
    #-------------------------------------------#
    data2 = pd.read_excel('2nd.xlsx') # MLMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('4th.xlsx') # LMHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 1 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('6th.xlsx') # HMMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('8th.xlsx') # HMMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 1 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('10th.xlsx') # MLLM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, 8, 8, 57))
    Result_Test_Y = session.run(y_pred, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 0 0 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 0.409996
Step 1000: Minibatch Loss: 0.352619
Step 2000: Minibatch Loss: 0.355774
Step 3000: Minibatch Loss: 0.384970
Step 4000: Minibatch Loss: 0.278612
Step 5000: Minibatch Loss: 0.403565
Step 6000: Minibatch Loss: 0.401917
Step 7000: Minibatch Loss: 0.029056
Step 8000: Minibatch Loss: 0.659364
Step 9000: Minibatch Loss: 0.074391
Step 10000: Minibatch Loss: 0.102747
Step 11000: Minibatch Loss: 0.022856
Step 12000: Minibatch Loss: 0.059984
Step 13000: Minibatch Loss: 0.083104
Step 14000: Minibatch Loss: 0.046836
Step 15000: Minibatch Loss: 0.097300
Step 16000: Minibatch Loss: 0.032168
Step 17000: Minibatch Loss: 0.016420
Step 18000: Minibatch Loss: 0.037425
Step 19000: Minibatch Loss: 0.009473
Step 20000: Minibatch Loss: 0.054590
Step 21000: Minibatch Loss: 0.001526
Step 22000: Minibatch Loss: 0.027773
Step 23000: Minibatch Loss: 0.061406
Step 24000: Minibatch Loss: 0.001769
Step 25000: Minibatch Loss: 0.014808
Step 26000: Minibatch Loss: 0.001605
Step 27000: Mi

47
Result of predicting EntireData
[[ 1.99293733  1.00048423  1.96073806  0.99051827]
 [ 1.98782003  1.00804436  2.00560498  1.02442956]
 [ 2.0208118   0.99337804  1.98257601  0.9844501 ]
 [ 1.87257779  1.00380111  2.00530481  0.98970693]
 [ 2.03929973  1.02703202  2.01698232  0.99266332]
 [ 1.94914603  1.00062788  2.00069761  0.97915006]
 [ 2.03441215  0.98873377  1.98854911  1.03456855]
 [ 1.94280434  1.00654113  1.9927249   1.00190413]
 [ 2.05303931  0.99111688  2.02550888  1.0143435 ]
 [ 1.94857395  0.99495542  2.01678395  1.02157116]]
48
Result of predicting EntireData
[[ 1.9364146   1.00872993  2.02214742  0.98225456]
 [ 1.98611224  0.98268116  1.96892154  1.0154115 ]
 [ 1.92411757  1.0116719   1.94720805  0.96071243]
 [ 1.92411757  1.0116719   1.94720805  0.96071243]
 [ 1.99497652  0.99617958  2.00654149  1.01922441]
 [ 1.94570076  1.00530446  2.03012943  1.00634372]
 [ 1.94570076  1.00530446  2.03012943  1.00634372]
 [ 1.96040714  1.01443458  1.93919146  0.99187523]
 [ 1.960407

95
Result of predicting EntireData
[[ 0.96928251  1.01271844 -0.01106113  1.98652339]
 [ 0.97421312  1.02123368 -0.01046687  2.01713395]
 [ 0.96993196  1.010427   -0.05860311  1.98132849]
 [ 0.96958697  1.02781248  0.05192326  2.06180453]
 [ 0.96822286  1.01927769  0.01642655  2.0084362 ]
 [ 0.97330904  1.01836181  0.00418779  2.01179671]
 [ 0.98791289  1.01235378 -0.00857919  1.9961468 ]
 [ 0.93237424  1.02571654  0.03350143  2.0112648 ]
 [ 0.97272587  1.02212203 -0.00313193  2.02595615]
 [ 0.99353468  1.01048243 -0.05457574  1.99073529]]
96
Result of predicting EntireData
[[  9.71068501e-01   1.01422179e+00   2.03698128e-02   2.01745510e+00]
 [  9.83602762e-01   1.01371562e+00   1.45719945e-02   2.00853491e+00]
 [  9.83963251e-01   1.01726723e+00   4.49461639e-02   2.05151820e+00]
 [  9.87922668e-01   1.01400745e+00   1.43086910e-02   2.03215742e+00]
 [  9.83054042e-01   1.01305699e+00  -1.62287354e-02   2.00109816e+00]
 [  9.82154846e-01   1.00252843e+00  -2.64328122e-02   1.9552394

Result of Test Data
0 0 1 1
[[ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  2.  1.]
 [ 

Result of Test Data
2 2 1 1
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 0.  2.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1. -0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 

Result of Test Data
1 2 1 2
[[ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 0.  1.  1.  2.]
 [ 

Result of Test Data
0 1 2 1
[[ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  1.  2.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 

Result of Test Data
2 1 1 1
[[ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 2. -0.  2.  1.]
 [ 