In [3]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
import random

os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [4]:
#Power Pressure Gas1 Gas2
data = pd.read_excel('2nd.xlsx') # MLMH
data = data.values
RealOESdata = data[151:251,1:]
data = pd.read_excel('4th.xlsx') # LMHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('6th.xlsx') # HMMH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('8th.xlsx') # HMMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('10th.xlsx') # MLLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('12th.xlsx') # LMML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('14th.xlsx') # MLHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('16th.xlsx') # HMML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('17th.xlsx') # LMLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('21th.xlsx') # HMHM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('23th.xlsx') # MLML
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('24th.xlsx') # HMLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('25th.xlsx') # LMMH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
####
data = pd.read_excel('1st.xlsx') # MMHH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('7th.xlsx') # MMLH
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('15th.xlsx') # LHMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('22th.xlsx') # MHLM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))
data = pd.read_excel('26th.xlsx') # MMMM
data = data.values
RealOESdata = np.vstack((RealOESdata, data[151:251,1:]))



In [5]:
Y_ClassifiedResult = np.array([1, 0, 1, 2])
for k in range(99):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 1, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 2, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 0, 1, 0])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([2, 1, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 1, 1, 2])))
##############################################
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 2, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 0, 2])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([0, 2, 1, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 2, 0, 1])))
for k in range(100):
    Y_ClassifiedResult = np.vstack((Y_ClassifiedResult,np.array([1, 1, 1, 1])))

Sequence = np.array([0])
for k in range(179):
    Sequence = np.hstack((Sequence, np.array([k+1])))

Sequence
#Y_ClassifiedResult = np.array([[1, 0, 1, 2],
#                            [0, 1, 2, 1],
#                            [2, 1, 1, 2],
#                            [2, 1, 1, 1],
#                            [1, 0, 0, 1],
#                            [0, 1, 1, 0],
#                            [1, 0, 2, 1],
#                            [2, 1, 1, 0],
#                            [0, 1, 0, 1],
#                            [2, 1, 2, 1],
#                            [1, 0, 1, 0],
#                            [2, 1, 0, 1],
#                            [0, 1, 1, 2]])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179])

# 1st

In [4]:
# Algorithm which decides standard for classifying data
# Algorithm which can detect some kind of different phenomena

learning_rate = 0.00001
tf.set_random_seed(777)

batchsize = 10

n_InputUnit = 3648
n_1stHiddenUnit = 500
n_2ndHiddenUnit = 300
n_3rdHiddenUnit = 250
n_4thHiddenUnit = 150
n_5thHiddenUnit = 50
n_OutputUnit = 4

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.01))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.01))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.01))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_4thHiddenUnit],stddev=0.01))
W5 = tf.Variable(tf.random_normal([n_4thHiddenUnit, n_5thHiddenUnit],stddev=0.01))
W6 = tf.Variable(tf.random_normal([n_5thHiddenUnit, n_OutputUnit],stddev=0.01))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_4thHiddenUnit], stddev=0.01))
b5 = tf.Variable(tf.random_normal([n_5thHiddenUnit], stddev=0.01))
b6 = tf.Variable(tf.random_normal([n_OutputUnit], stddev=0.01))

X = tf.placeholder(tf.float32, [None, n_InputUnit]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None, n_OutputUnit])

L1 = tf.nn.elu(tf.matmul(X, W1) + b1)
L2 = tf.nn.elu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.elu(tf.matmul(L2, W3) + b3)
L4 = tf.nn.elu(tf.matmul(L3, W4) + b4)
L5 = tf.nn.elu(tf.matmul(L4, W5) + b5)
Hypothesis = tf.nn.elu(tf.matmul(L5, W6) + b6)

cost = tf.reduce_mean(tf.pow(Y - Hypothesis, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate,beta1=0.5).minimize(cost)

In [7]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range(100001):
        Order = Sequence[step % 170]
        
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_InputUnit)) #25개
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_OutputUnit))
        
        _, MinibatchLoss = session.run([train, cost], feed_dict ={X: batch_X, Y: batch_Y})
        #####################################
        #print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
        
        #####################################
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
            
        if step % 170 == 0:
            random.shuffle(Sequence)
            
            
    for i in range(170):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, n_InputUnit))
        PredictedBatchData = session.run(Hypothesis, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, n_OutputUnit))
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
        
    
   # print("R_square of EntireData")
   # print(r2_score(Y_ClassifiedResult, PredictedEntireData))
    ############################################################################
    
    #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 0.520831
Step 1000: Minibatch Loss: 0.553410
Step 2000: Minibatch Loss: 0.274142
Step 3000: Minibatch Loss: 0.355800
Step 4000: Minibatch Loss: 0.522078
Step 5000: Minibatch Loss: 0.640655
Step 6000: Minibatch Loss: 0.567029
Step 7000: Minibatch Loss: 0.134747
Step 8000: Minibatch Loss: 0.435665
Step 9000: Minibatch Loss: 0.122891
Step 10000: Minibatch Loss: 0.377760
Step 11000: Minibatch Loss: 0.140893
Step 12000: Minibatch Loss: 0.035156
Step 13000: Minibatch Loss: 0.277416
Step 14000: Minibatch Loss: 0.512020
Step 15000: Minibatch Loss: 0.021486
Step 16000: Minibatch Loss: 0.070607
Step 17000: Minibatch Loss: 0.358927
Step 18000: Minibatch Loss: 0.043178
Step 19000: Minibatch Loss: 0.066979
Step 20000: Minibatch Loss: 0.009090
Step 21000: Minibatch Loss: 0.002208
Step 22000: Minibatch Loss: 0.011889
Step 23000: Minibatch Loss: 0.031248
Step 24000: Minibatch Loss: 0.135548
Step 25000: Minibatch Loss: 0.018685
Step 26000: Minibatch Loss: 0.045085
Step 27000: Mi

50
Result of predicting EntireData
[[-0.088889    1.14944911  1.09479272  0.24000901]
 [-0.06809831  1.11395931  1.08545911  0.22238803]
 [-0.07128984  1.14016509  1.09589064  0.23861843]
 [-0.08068377  1.13388228  1.09276044  0.23153983]
 [-0.06543392  1.13185823  1.09473896  0.23439139]
 [-0.08366197  1.15520525  1.09472454  0.24578495]
 [-0.08869195  1.14769673  1.09387732  0.23990521]
 [-0.07851237  1.14714742  1.0955795   0.24200304]
 [-0.06876147  1.13349354  1.09377396  0.23508385]
 [-0.05820578  1.14015567  1.0956068   0.24240543]]
Result of Rounded off EntireData
[[-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]
 [-0.  1.  1.  0.]]
Original Data
[0 1 1 0]
51
Result of predicting EntireData
[[-0.08971304  1.15341973  1.09478593  0.24288554]
 [-0.05842727  1.1304605   1.09544373  0.23456368]
 [-0.06903273  1.11386728  1.08651853  0.22123945]
 [-0.06358832  1.1

99
Result of predicting EntireData
[[ 1.50670111  0.97475392  1.69711673  0.6717577 ]
 [ 1.53098488  0.96509385  1.70011353  0.66887528]
 [ 1.49302578  0.98667467  1.68941641  0.66984671]
 [ 1.47697389  0.98351544  1.69768524  0.67816907]
 [ 1.53016174  0.98216265  1.68837667  0.66054881]
 [ 1.46724546  0.99027413  1.69455445  0.67759371]
 [ 1.49057567  1.00026369  1.68406427  0.66512531]
 [ 1.50625598  0.96836466  1.70002127  0.67481232]
 [ 1.44351315  0.98969966  1.69715428  0.68460649]
 [ 1.48390543  0.98943275  1.69499934  0.67379135]]
100
Result of predicting EntireData
[[ 1.18922675  0.22606821  0.99646777  0.02173686]
 [ 1.24421036  0.25710577  0.99378365  0.02193979]
 [ 1.24066961  0.2566798   0.99314696  0.02139521]
 [ 1.27995121  0.28055546  0.99456936  0.01694158]
 [ 1.18258977  0.21904214  0.99198002  0.02873546]
 [ 1.18550789  0.22260924  0.99437422  0.0255389 ]
 [ 1.23345828  0.25536278  0.99554175  0.01642046]
 [ 1.23673737  0.25356355  0.99476618  0.02182141]
 [ 1.20301

159
Result of predicting EntireData
[[-0.2756905   1.86240315  0.94708437  0.77593964]
 [-0.27815169  1.86294937  0.94589597  0.77395999]
 [-0.27420616  1.86094213  0.94629091  0.77428812]
 [-0.30860102  1.86628878  0.93242502  0.75716799]
 [-0.27824777  1.85420251  0.94026458  0.76439977]
 [-0.27824777  1.85420251  0.94026458  0.76439977]
 [-0.26513731  1.80239177  0.94367129  0.72194189]
 [-0.29671979  1.86618137  0.93724394  0.76592106]
 [-0.27896315  1.84881568  0.93863624  0.75637847]
 [-0.27896315  1.84881568  0.93863624  0.75637847]]
160
Result of predicting EntireData
[[ 0.24777855  1.18270445  0.70042652  1.45512855]
 [ 0.23728375  1.18441975  0.66939455  1.44328022]
 [ 0.25043049  1.183249    0.68869984  1.44340837]
 [ 0.23416382  1.18775129  0.65617806  1.43897903]
 [ 0.23955984  1.1853689   0.67758578  1.44824469]
 [ 0.24530266  1.18516123  0.69315529  1.4540782 ]
 [ 0.24844636  1.18326914  0.67310673  1.43285871]
 [ 0.24479394  1.18515658  0.68461841  1.44813466]
 [ 0.2425

Result of Test Data
[[ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  

# 2nd

In [8]:
# Algorithm which decides standard for classifying data
# Algorithm which can detect some kind of different phenomena

learning_rate = 0.00001
tf.set_random_seed(777)

batchsize = 10

n_InputUnit = 3648
n_1stHiddenUnit = 500
n_2ndHiddenUnit = 300
n_3rdHiddenUnit = 250
n_OutputUnit = 4

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.01))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.01))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.01))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_OutputUnit],stddev=0.01))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_OutputUnit], stddev=0.01))

X = tf.placeholder(tf.float32, [None, n_InputUnit]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None, n_OutputUnit])

L1 = tf.nn.elu(tf.matmul(X, W1) + b1)
L2 = tf.nn.elu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.elu(tf.matmul(L2, W3) + b3)
Hypothesis = tf.nn.elu(tf.matmul(L3, W4) + b4)

cost = tf.reduce_mean(tf.pow(Y - Hypothesis, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate,beta1=0.5).minimize(cost)

In [9]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range(50001):
        Order = Sequence[step % 170]
        
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_InputUnit)) #25개
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_OutputUnit))
        
        _, MinibatchLoss = session.run([train, cost], feed_dict ={X: batch_X, Y: batch_Y})
        #####################################
        #print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
        
        #####################################
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
            
        if step % 170 == 0:
            random.shuffle(Sequence)
            
            
    for i in range(170):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, n_InputUnit))
        PredictedBatchData = session.run(Hypothesis, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, n_OutputUnit))
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
        
    
   # print("R_square of EntireData")
   # print(r2_score(Y_ClassifiedResult, PredictedEntireData))
    ############################################################################
    
    #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 27.685627
Step 1000: Minibatch Loss: 1.373689
Step 2000: Minibatch Loss: 0.256328
Step 3000: Minibatch Loss: 0.143828
Step 4000: Minibatch Loss: 0.288538
Step 5000: Minibatch Loss: 0.637720
Step 6000: Minibatch Loss: 0.674257
Step 7000: Minibatch Loss: 0.541116
Step 8000: Minibatch Loss: 0.253699
Step 9000: Minibatch Loss: 0.240466
Step 10000: Minibatch Loss: 0.218307
Step 11000: Minibatch Loss: 0.526664
Step 12000: Minibatch Loss: 0.101544
Step 13000: Minibatch Loss: 0.109660
Step 14000: Minibatch Loss: 0.298987
Step 15000: Minibatch Loss: 0.116655
Step 16000: Minibatch Loss: 0.074012
Step 17000: Minibatch Loss: 0.156459
Step 18000: Minibatch Loss: 0.159133
Step 19000: Minibatch Loss: 0.100674
Step 20000: Minibatch Loss: 0.014957
Step 21000: Minibatch Loss: 0.179483
Step 22000: Minibatch Loss: 0.027752
Step 23000: Minibatch Loss: 0.064801
Step 24000: Minibatch Loss: 0.025554
Step 25000: Minibatch Loss: 0.384956
Step 26000: Minibatch Loss: 0.073614
Step 27000: M

48
Result of predicting EntireData
[[ 0.98036355  0.02376556 -0.03015637  1.01256239]
 [ 0.98458809  0.03408366 -0.04283196  1.01010931]
 [ 0.97336185  0.03357261 -0.05050904  1.01258445]
 [ 0.97827476  0.01604026 -0.02712291  1.01402354]
 [ 0.97984582  0.02412903 -0.04782641  1.01087737]
 [ 0.98461086  0.03180629 -0.0335902   1.01352084]
 [ 0.98088413  0.04042804 -0.04003441  1.01758325]
 [ 0.98060215  0.04338783 -0.0278765   1.01258039]
 [ 0.97803938  0.04437601 -0.05004632  1.01299393]
 [ 0.98036569  0.02130735 -0.03544438  1.01606214]]
49
Result of predicting EntireData
[[ 0.97706985  0.02494263 -0.04603481  1.00339615]
 [ 0.97799838  0.0378806  -0.03337818  1.00467646]
 [ 0.96727329  0.01482743 -0.04142421  1.01974273]
 [ 0.97985899  0.0155462  -0.02010906  1.01602805]
 [ 0.98217642  0.02582818 -0.05720347  1.01191533]
 [ 0.9853248   0.05222547 -0.05199128  1.01054919]
 [ 0.96123427  0.02056134 -0.04693121  1.01184428]
 [ 0.9830519   0.026681   -0.05350161  1.00059509]
 [ 0.974860

108
Result of predicting EntireData
[[ 1.43131983  0.33252388  1.01619172 -0.01679558]
 [ 1.41804266  0.31647825  1.00257432 -0.00659424]
 [ 1.40859079  0.29760456  1.01931548 -0.00815803]
 [ 1.40859079  0.29760456  1.01931548 -0.00815803]
 [ 1.3887645   0.27878246  1.01444697 -0.01314282]
 [ 1.3887645   0.27878246  1.01444697 -0.01314282]
 [ 1.48141837  0.35977244  1.01230788 -0.00226903]
 [ 1.42062497  0.31686294  1.00928354  0.00425022]
 [ 1.41778111  0.30355722  1.02860928 -0.01680183]
 [ 1.44147277  0.32328838  1.0235256   0.00224094]]
109
Result of predicting EntireData
[[  1.45207214e+00   3.44918638e-01   1.01466048e+00  -8.06534290e-03]
 [  1.51612234e+00   3.95331383e-01   1.03659940e+00  -1.70767903e-02]
 [  1.43736935e+00   3.42565686e-01   1.01011848e+00  -7.21949339e-03]
 [  1.43736935e+00   3.42565686e-01   1.01011848e+00  -7.21949339e-03]
 [  1.45340085e+00   3.48017991e-01   1.01143146e+00  -1.22269988e-02]
 [  1.49372530e+00   4.05205995e-01   1.00608051e+00  -8.01271

162
Result of predicting EntireData
[[ 0.84219617  1.75309694  0.2545341   1.22147644]
 [ 0.8509534   1.75541139  0.26023206  1.22814333]
 [ 0.84990621  1.73699796  0.2657564   1.21622491]
 [ 0.85303998  1.74518287  0.28432241  1.26020813]
 [ 0.83415264  1.76270425  0.21329482  1.20405281]
 [ 0.82606208  1.73714304  0.29289001  1.25756407]
 [ 0.84964532  1.73717952  0.30126122  1.25513136]
 [ 0.82411492  1.75293314  0.25067526  1.21928728]
 [ 0.8711893   1.75703359  0.25232309  1.21995497]
 [ 0.81875211  1.72044444  0.28047916  1.23877966]]
163
Result of predicting EntireData
[[ 0.8560279   1.75277495  0.26822171  1.22904503]
 [ 0.81178665  1.71501815  0.2635251   1.23125327]
 [ 0.83606088  1.73041844  0.29401681  1.2590543 ]
 [ 0.85554725  1.76245165  0.22199525  1.19085014]
 [ 0.86117977  1.78144765  0.21434473  1.1952951 ]
 [ 0.83467364  1.73014557  0.24337544  1.21650863]
 [ 0.87536854  1.78195763  0.21770488  1.19105899]
 [ 0.84978777  1.75515413  0.19614501  1.17367661]
 [ 0.8668

Result of Test Data
1 1 0 0
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 2 1
[[-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-

Result of Test Data
1 2 1 2
[[ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 

# 3rd

In [10]:
# Algorithm which decides standard for classifying data
# Algorithm which can detect some kind of different phenomena

learning_rate = 0.00001
tf.set_random_seed(777)

batchsize = 10

n_InputUnit = 3648
n_1stHiddenUnit = 500
n_2ndHiddenUnit = 300
n_3rdHiddenUnit = 250
n_OutputUnit = 4

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.01))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.01))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.01))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_OutputUnit],stddev=0.01))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_OutputUnit], stddev=0.01))

X = tf.placeholder(tf.float32, [None, n_InputUnit]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None, n_OutputUnit])

L1 = tf.nn.elu(tf.matmul(X, W1) + b1)
L2 = tf.nn.elu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.elu(tf.matmul(L2, W3) + b3)
Hypothesis = tf.nn.elu(tf.matmul(L3, W4) + b4)

cost = tf.reduce_mean(tf.pow(Y - Hypothesis, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate,beta1=0.5).minimize(cost)

In [11]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range(200001):
        Order = Sequence[step % 170]
        
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_InputUnit)) #25개
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_OutputUnit))
        
        _, MinibatchLoss = session.run([train, cost], feed_dict ={X: batch_X, Y: batch_Y})
        #####################################
        #print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
        
        #####################################
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
            
        if step % 170 == 0:
            random.shuffle(Sequence)
            
            
    for i in range(170):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, n_InputUnit))
        PredictedBatchData = session.run(Hypothesis, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, n_OutputUnit))
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
        
    
   # print("R_square of EntireData")
   # print(r2_score(Y_ClassifiedResult, PredictedEntireData))
    ############################################################################
    
    #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

Step 0: Minibatch Loss: 48.566551
Step 1000: Minibatch Loss: 0.299528
Step 2000: Minibatch Loss: 0.091093
Step 3000: Minibatch Loss: 0.554920
Step 4000: Minibatch Loss: 0.185050
Step 5000: Minibatch Loss: 0.105284
Step 6000: Minibatch Loss: 0.376890
Step 7000: Minibatch Loss: 0.478577
Step 8000: Minibatch Loss: 0.058584
Step 9000: Minibatch Loss: 0.221126
Step 10000: Minibatch Loss: 0.472085
Step 11000: Minibatch Loss: 0.432402
Step 12000: Minibatch Loss: 0.368067
Step 13000: Minibatch Loss: 0.471401
Step 14000: Minibatch Loss: 0.585288
Step 15000: Minibatch Loss: 0.067618
Step 16000: Minibatch Loss: 0.001732
Step 17000: Minibatch Loss: 0.660882
Step 18000: Minibatch Loss: 0.039242
Step 19000: Minibatch Loss: 0.141706
Step 20000: Minibatch Loss: 0.025765
Step 21000: Minibatch Loss: 0.192844
Step 22000: Minibatch Loss: 0.377310
Step 23000: Minibatch Loss: 0.123970
Step 24000: Minibatch Loss: 0.186890
Step 25000: Minibatch Loss: 0.027426
Step 26000: Minibatch Loss: 0.287602
Step 27000: M

48
Result of predicting EntireData
[[ 1.00132215  0.03267125  0.00512215  0.96500129]
 [ 0.99257648  0.02665142  0.00500282  0.96374118]
 [ 0.99606568  0.03396831  0.0141805   0.96935636]
 [ 0.98710871  0.01944218  0.01642629  0.96517807]
 [ 0.99940032  0.02515022  0.00718787  0.95935112]
 [ 1.0009023   0.03949074  0.00917124  0.96513587]
 [ 1.00084424  0.02412609  0.00430491  0.95821291]
 [ 1.00036728  0.03566799  0.00633495  0.96563274]
 [ 0.99734467  0.03181121  0.00532716  0.95951527]
 [ 0.99585974  0.02654222  0.0125032   0.9554854 ]]
49
Result of predicting EntireData
[[  9.96519685e-01   2.39292160e-02   4.67117922e-03   9.57132995e-01]
 [  1.00093913e+00   2.75322571e-02   1.11038610e-02   9.62448776e-01]
 [  9.90467310e-01   2.39603892e-02   1.10468492e-02   9.58641708e-01]
 [  9.85491872e-01   3.78709808e-02   1.84566602e-02   9.74193573e-01]
 [  9.95620251e-01   1.87787786e-02   2.16474431e-03   9.60520148e-01]
 [  9.94853139e-01   3.37619558e-02   7.87993520e-03   9.6568119

99
Result of predicting EntireData
[[ 2.15469694  1.04364479  1.97804713  0.94432074]
 [ 2.15686679  1.03678358  1.98214293  0.95304763]
 [ 2.14976811  1.05052316  2.00025988  0.96858197]
 [ 2.12100506  1.04038477  2.00487328  0.99604243]
 [ 2.16251302  1.05108225  1.97873688  0.95461941]
 [ 2.1360116   1.04346204  2.00785685  0.98408949]
 [ 2.14696503  1.04676461  2.00815916  0.96119875]
 [ 2.14834404  1.0411514   1.98519051  0.97342688]
 [ 2.12485766  1.0417217   2.01250267  0.99960893]
 [ 2.14395976  1.048895    2.00939536  0.97760737]]
100
Result of predicting EntireData
[[ 1.01358771 -0.03948653  0.96482253 -0.10362881]
 [ 1.00868726 -0.04930347  0.96886444 -0.09591395]
 [ 1.02592814 -0.02419806  0.97140217 -0.08633989]
 [ 1.02222764 -0.01788801  0.9739362  -0.07996082]
 [ 0.97138411 -0.07163197  0.97582364 -0.0794186 ]
 [ 0.9977693  -0.05309665  0.96740556 -0.09675068]
 [ 1.03437459 -0.01537019  0.97029996 -0.0985716 ]
 [ 1.01086724 -0.03810853  0.97201908 -0.09482163]
 [ 0.98769

152
Result of predicting EntireData
[[ 0.10160562  2.04572892  1.02917647  1.04428518]
 [ 0.08410916  2.01982331  1.01906705  1.01240218]
 [ 0.12507814  1.98842037  1.02913547  1.0093416 ]
 [ 0.09194159  2.02059126  1.02359247  1.02136278]
 [ 0.13918634  2.04277611  1.05368447  1.06003416]
 [ 0.11505067  2.04649806  1.03469419  1.05469358]
 [ 0.10073192  2.06296182  1.04230821  1.08523309]
 [ 0.13708584  2.05769229  1.06119132  1.0913986 ]
 [ 0.13708584  2.05769229  1.06119132  1.0913986 ]
 [ 0.12496953  2.04096794  1.07308352  1.08359194]]
153
Result of predicting EntireData
[[ 0.13710697  2.03383374  1.07816648  1.09462035]
 [ 0.13710697  2.03383374  1.07816648  1.09462035]
 [ 0.20473561  2.00367951  1.10359323  1.08084834]
 [ 0.15546411  2.04430556  1.08336222  1.11513805]
 [ 0.14569837  2.03496003  1.07664561  1.0926615 ]
 [ 0.11930814  2.05242181  1.06205201  1.10060608]
 [ 0.11930814  2.05242181  1.06205201  1.10060608]
 [ 0.17926784  2.01388073  1.07662964  1.06539738]
 [ 0.1475

Result of Test Data
0 0 1 1
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  0.  1.]
 [ 

Result of Test Data
2 2 1 1
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 

Result of Test Data
1 2 1 0
[[-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-0.  1.  1. -0.]
 [-

# 4th

In [10]:
# Algorithm which decides standard for classifying data
# Algorithm which can detect some kind of different phenomena

learning_rate = 0.0000001
tf.set_random_seed(777)

batchsize = 10

n_InputUnit = 3648
n_1stHiddenUnit = 500
n_2ndHiddenUnit = 300
n_3rdHiddenUnit = 250
n_OutputUnit = 4

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.01))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.01))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.01))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_OutputUnit],stddev=0.01))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_OutputUnit], stddev=0.01))

X = tf.placeholder(tf.float32, [None, n_InputUnit]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None, n_OutputUnit])

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
Hypothesis = tf.nn.relu(tf.matmul(L3, W4) + b4)

cost = tf.reduce_mean(tf.pow(Y - Hypothesis, 2))
train = tf.train.AdamOptimizer(learning_rate=learning_rate,beta1=0.5).minimize(cost)

In [1]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range(200001):
        Order = Sequence[step % 170]
        
        batch_X = np.reshape(RealOESdata[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_InputUnit)) #25개
        
        batch_Y = np.reshape(Y_ClassifiedResult[Order*batchsize: (Order+1)*batchsize,:],
                             (batchsize, n_OutputUnit))
        
        _, MinibatchLoss = session.run([train, cost], feed_dict ={X: batch_X, Y: batch_Y})
        #####################################
        #print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
        
        #####################################
        if step % 1000 == 0:
            print ('Step %i: Minibatch Loss: %f' % (step, MinibatchLoss))
            
        if step % 170 == 0:
            random.shuffle(Sequence)
            
            
    for i in range(170):
        Result_batch_X = np.reshape(RealOESdata[i*batchsize: (i+1)*batchsize,:],
                                    (batchsize, n_InputUnit))
        PredictedBatchData = session.run(Hypothesis, feed_dict = {X : Result_batch_X})
        Y_ClassifiedResult_Reshaped = np.reshape(Y_ClassifiedResult[i*batchsize: (i+1)*batchsize,:],
                                                 (batchsize, n_OutputUnit))
        
        print(i)
        print("Result of predicting EntireData")
        print(PredictedBatchData)
        
        if i % 10 == 0:
            print("Result of Rounded off EntireData")
            print(np.rint(PredictedBatchData))
            print("Original Data")
            print(Y_ClassifiedResult_Reshaped[1,:])
        
        if i == 0:
            PredictedEntireData = PredictedBatchData
        else:
            PredictedEntireData = np.vstack((PredictedEntireData,PredictedBatchData))
        
    
   # print("R_square of EntireData")
   # print(r2_score(Y_ClassifiedResult, PredictedEntireData))
    ############################################################################
    
    #-------------------------------------------#
    data2 = pd.read_excel('3rd.xlsx') # LLMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("0 0 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('9th.xlsx') # MMLL
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 1 0 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('13th.xlsx') # HHMM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("2 2 1 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('18th.xlsx') # MHHM
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 2 1")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('19th.xlsx') # MHML
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 0")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)
    
    #-------------------------------------------#
    data2 = pd.read_excel('27th.xlsx') # MHMH
    data2 = data2.values
    TestOESdata = data2[151:251,1:]
    
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print("1 2 1 2")
    print(np.rint(Result_Test_Y))
    print(Result_Test_Y)

NameError: name 'tf' is not defined

In [46]:
data2 = pd.read_excel('11th.xlsx') # MMHL
data2 = data2.values
TestOESdata = data2[151:251,1:]

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    Result_Test_X = np.reshape(TestOESdata, (100, n_InputUnit))
    Result_Test_Y = session.run(Hypothesis, feed_dict = {X : Result_Test_X})
    
    print("Result of Test Data")
    print(np.rint(Result_Test_Y))

ValueError: cannot reshape array of size 0 into shape (100,3648)