In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import statsmodels.formula.api as sm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn import cross_validation
import tensorflow as tf

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data = np.genfromtxt('acl data.txt') # The default path is same with this ipynb

X_before = data[:,0:4] #The ":" means include whole range of array. 0:4 means to include numbers from 0th to 3rd column.
Y_before = data[:,4] #4 means to include numbers from 4th column.
X = (X_before-np.min(X_before))/(np.max(X_before)-np.min(X_before))
Y = (Y_before-min(Y_before))/(max(Y_before)-min(Y_before))   #nomalizing
# 배치 전체를 normalize? 하나의 수로?

dfX=pd.DataFrame(X) #Include X to dfX, and make it to table type.
dfy=pd.DataFrame(Y)

table=pd.concat([dfX, dfy], axis=1) #If axis = 1, then concat to right side. Otherwise (axis = 0), then concat to bottom side.
                                    #Also, if they have sharing indexes or columns, then it will be write on the same indexes or columns.
                                    #But, if it doesn't, then it will be write on the different indexes or columns, 
                                    #and it will be appear as NaN in the not shared parameters.
table.columns=['Power','Pressure','C3H6','N2','Thickness_Top'] #P

table

Power  Pressure      C3H6        N2  Thickness_Top
0   0.188034   0.82906  0.059829  0.017094       0.292727
1   0.188034   0.65812  0.042735  0.017094       0.000000
2   0.170940   0.65812  0.042735  0.008547       0.051818
3   0.170940   0.82906  0.059829  0.008547       0.256364
4   0.188034   0.82906  0.042735  0.008547       0.409091
5   0.205128   0.82906  0.042735  0.017094       0.272727
6   0.188034   0.82906  0.025641  0.017094       0.582727
7   0.205128   0.65812  0.042735  0.008547       0.138182
8   0.188034   0.82906  0.025641  0.000000       0.589091
9   0.188034   0.65812  0.025641  0.008547       0.278182
10  0.188034   0.82906  0.059829  0.000000       0.392727
11  0.170940   0.82906  0.042735  0.000000       0.530000
12  0.205128   1.00000  0.042735  0.008547       1.000000
13  0.188034   0.65812  0.059829  0.008547       0.089091
14  0.170940   1.00000  0.042735  0.008547       0.648182
15  0.205128   0.82906  0.042735  0.000000       0.337273
16  0.170940   0.82906  0.025641  0.008547       0.576364
17  0.188034   1.00000  0.059829  0.008547       0.468182
18  0.188034   1.00000  0.042735  0.000000       0.617273
19  0.188034   0.82906  0.042735  0.008547       0.320000
20  0.205128   0.82906  0.059829  0.008547       0.260000
21  0.188034   1.00000  0.025641  0.008547       0.853636
22  0.188034   0.65812  0.042735  0.000000       0.099091
23  0.205128   0.82906  0.025641  0.008547       0.640000
24  0.170940   0.82906  0.042735  0.017094       0.340909
25  0.188034   0.82906  0.042735  0.008547       0.383636
26  0.188034   1.00000  0.042735  0.017094       0.560000

In [3]:
X_train, X_test, Y_train, Y_test = cross_validation.train_test_split(
X, Y, test_size=0.14,random_state=0)

In [4]:
print("X_train : ") #unnormalize
print(X_train*(np.max(X_before)-np.min(X_before))+np.min(X_before))
print("Y_train : ")
print(Y_train*(np.max(Y_before)-np.min(Y_before))+np.min(Y_before))
print("X_test : ")
print(X_test*(np.max(X_before)-np.min(X_before))+np.min(X_before))
print("Y_test : ")
print(Y_test*(np.max(Y_before)-np.min(Y_before))+np.min(Y_before))

X_train : 
[[  270.  1000.    80.    50.]
 [  230.  1000.    80.    30.]
 [  270.  1000.    60.    40.]
 [  250.   800.   100.    40.]
 [  250.  1000.    80.    40.]
 [  270.  1000.   100.    40.]
 [  230.  1000.    60.    40.]
 [  250.   800.    80.    50.]
 [  250.  1000.   100.    30.]
 [  250.  1200.    80.    50.]
 [  250.  1000.    80.    40.]
 [  250.  1000.    60.    30.]
 [  250.  1000.    60.    50.]
 [  250.  1000.    80.    40.]
 [  250.  1200.    80.    30.]
 [  250.   800.    60.    40.]
 [  270.   800.    80.    40.]
 [  250.   800.    80.    30.]
 [  230.  1000.   100.    40.]
 [  250.  1000.   100.    50.]
 [  250.  1200.    60.    40.]
 [  270.  1000.    80.    30.]
 [  270.  1200.    80.    40.]]
Y_train : 
[ 1001.  1284.  1405.   799.  1053.   987.  1335.   701.  1133.  1317.
  1123.  1349.  1342.  1151.  1380.  1007.   853.   810.   983.  1023.
  1640.  1072.  1801.]
X_test : 
[[  230.   800.    80.    40.]
 [  230.  1000.    80.    50.]
 [  230.  1200.    80.    4

In [5]:
import tensorflow as tf

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.01

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, ])

W1 = tf.Variable(tf.random_normal([4, 3]), name='weight1')
b1 = tf.Variable(tf.random_normal([3]), name='bias1')
layer1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([3, 4]), name='weight2')
b2 = tf.Variable(tf.random_normal([4]), name='bias2')
layer2 = tf.nn.relu(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([4, 3]), name='weight3')
b3 = tf.Variable(tf.random_normal([3]), name='bias3')
layer3 = tf.nn.relu(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([3, 2]), name='weight4')
b4 = tf.Variable(tf.random_normal([2]), name='bias4')
layer4 = tf.nn.relu(tf.matmul(layer3, W4) + b4)

W5 = tf.Variable(tf.random_normal([2, 1]), name='weight5')
b5 = tf.Variable(tf.random_normal([1]), name='bias5')
hypothesis = tf.nn.sigmoid(tf.matmul(layer4, W5) + b5) #hypothesis is y_predict

# cost/loss function
# cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))<-Logistic
cost = tf.reduce_mean(tf.square(hypothesis - Y)) # <-MSE

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)
                #AdamOptimizer(...)...

# Accuracy computation
# True if hypothesis>0.5 else False
# predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
# accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y_test), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(20000):
        sess.run(train, feed_dict={X: X_train, Y: Y_train})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: X_train, Y: Y_train})) #, sess.run([W1, W2]))

    # Accuracy report
    # h, c, a = sess.run([hypothesis, predicted, accuracy],
    #                   feed_dict={X: X_test, Y: Y_test})
    
    h = sess.run( hypothesis, feed_dict={X: X_test, Y: Y_test})
    
    print("\nHypothesis: ", h)
    #print( "\nCorrect: ", c)
    #print("\nAccuracy: ", a)
    print("\nrealY: ", Y_test)

    print("\nHypothesis: ")
    print(h*(np.max(Y_before)-np.min(Y_before))+np.min(Y_before))

    print("realY")
    print(Y_test*(np.max(Y_before)-np.min(Y_before))+np.min(Y_before))
    
    mse = mean_squared_error(Y_test, h)
    print("MSE: %.4f" % mse)

    a = r2_score(Y_test,h)
    print("R2: %.4f" % a)

0 0.0712354
100 0.0585779
200 0.0574977
300 0.0574027
400 0.0573922
500 0.05739
600 0.057389
700 0.0573879
800 0.0573869
900 0.0573862
1000 0.0573859
1100 0.0573857
1200 0.0573855
1300 0.0573855
1400 0.0573854
1500 0.0573854
1600 0.0573853
1700 0.0573853
1800 0.0573853
1900 0.0573852
2000 0.0573852
2100 0.0573852
2200 0.0573852
2300 0.0573851
2400 0.0573851
2500 0.0573851
2600 0.0573851
2700 0.0573851
2800 0.057385
2900 0.057385
3000 0.057385
3100 0.057385
3200 0.0573849
3300 0.0573849
3400 0.0573849
3500 0.0573849
3600 0.0573849
3700 0.0573848
3800 0.0573848
3900 0.0573848
4000 0.0573848
4100 0.0573847
4200 0.0573847
4300 0.0573847
4400 0.0573847
4500 0.0573847
4600 0.0573846
4700 0.0573846
4800 0.0573846
4900 0.0573846
5000 0.0573845
5100 0.0573845
5200 0.0573845
5300 0.0573845
5400 0.0573844
5500 0.0573844
5600 0.0573844
5700 0.0573844
5800 0.0573844
5900 0.0573843
6000 0.0573843
6100 0.0573843
6200 0.0573843
6300 0.0573843
6400 0.0573842
6500 0.0573842
6600 0.0573842
6700 0.0573842