In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
import pandas as pd
import os
import random

os.environ["CUDA_VISIBLE_DEVICES"]="-1"

# Import Data (normalized) & Separate to Training and Test

In [3]:
data = np.loadtxt("ACL nomalization data.txt")
data2 = np.loadtxt("acl data.txt")

Y_OriginalData = data2[:,4]

X_NormalizedData = data[:,0:4]
Y_NormalizedData = data[:,4]

#Y_NormalizedData = (Y_OriginalData-np.mean(Y_OriginalData))/(max(Y_OriginalData)-min(Y_OriginalData))

X_TrainingData = data[0:21,0:4]
Y_TrainingData = data[0:21,4]

X_TestData = data[21:,0:4]
Y_TestData = data[21:,4]

Sequence = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

#XY_TrainingData = data[0:21,:]
#X_TrainingData = XY_TrainingData[0:21,0:4]
#Y_TrainingData = XY_TrainingData[0:21,4]
#
#XY_TestData = data[21:,:]
#X_TestData = XY_TestData[:,0:4]
#Y_TestData = XY_TestData[:,4]

print(X_TrainingData)
print("------------------------")
print(X_TestData)
print("------------------------")
print(Y_TrainingData)
print("------------------------")
print(Y_TestData)
print(np.mean(Y_OriginalData))

[[ 0.   0.   0.5  0.5]
 [ 0.  -0.5  0.   0.5]
 [-0.5 -0.5  0.   0. ]
 [-0.5  0.   0.5  0. ]
 [ 0.   0.   0.   0. ]
 [ 0.5  0.   0.   0.5]
 [ 0.   0.  -0.5  0.5]
 [ 0.5 -0.5  0.   0. ]
 [ 0.   0.  -0.5 -0.5]
 [ 0.  -0.5 -0.5  0. ]
 [ 0.   0.   0.5 -0.5]
 [-0.5  0.   0.  -0.5]
 [ 0.5  0.5  0.   0. ]
 [ 0.  -0.5  0.5  0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5  0.   0.  -0.5]
 [-0.5  0.  -0.5  0. ]
 [ 0.   0.5  0.5  0. ]
 [ 0.   0.5  0.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.5  0.   0.5  0. ]]
------------------------
[[ 0.   0.5 -0.5  0. ]
 [ 0.  -0.5  0.  -0.5]
 [ 0.5  0.  -0.5  0. ]
 [-0.5  0.   0.   0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.5]]
------------------------
[-0.11420875 -0.40693603 -0.35511784 -0.15057239  0.00215488 -0.13420875
  0.17579125 -0.26875421  0.18215488 -0.12875421 -0.01420875  0.12306397
  0.59306397 -0.31784512  0.24124579 -0.0696633   0.16942761  0.06124579
  0.2103367  -0.08693603 -0.14693603]
------------------------
[ 0.44670034 -0.30784512  0.23306397 -0.06602

# Define Parameters of my NN Model

## 1st

In [4]:
learning_rate = 0.00001

n_InputUnit = 4
n_1stHiddenUnit=18
n_2ndHiddenUnit=18
n_3rdHiddenUnit=9
n_4thHiddenUnit=9
n_OutputUnit = 1

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.1))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.1))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.1))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_4thHiddenUnit],stddev=0.1))
W5 = tf.Variable(tf.random_normal([n_4thHiddenUnit, n_OutputUnit],stddev=0.1))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], mean = 0, stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], mean = 0, stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], mean = 0, stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_4thHiddenUnit], mean = 0, stddev=0.01))
b5 = tf.Variable(tf.random_normal([n_OutputUnit], mean = 0, stddev=0.01))

X = tf.placeholder(tf.float32, [None, 4]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None,])

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
Hypothesis = tf.nn.relu(tf.matmul(L4, W5) + b5)

cost = tf.reduce_mean((Y-Hypothesis)*(Y-Hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

### 1st-1

In [5]:
learning_rate = 0.00001

n_InputUnit = 4
n_1stHiddenUnit=18
n_2ndHiddenUnit=18
n_3rdHiddenUnit=9
n_4thHiddenUnit=9
n_OutputUnit = 1

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.1))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.1))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.1))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_4thHiddenUnit],stddev=0.1))
W5 = tf.Variable(tf.random_normal([n_4thHiddenUnit, n_OutputUnit],stddev=0.1))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], mean = 0, stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], mean = 0, stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], mean = 0, stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_4thHiddenUnit], mean = 0, stddev=0.01))
b5 = tf.Variable(tf.random_normal([n_OutputUnit], mean = 0, stddev=0.01))

X = tf.placeholder(tf.float32, [None, 4]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None,])

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
Hypothesis = tf.nn.relu(tf.matmul(L4, W5) + b5)

cost = tf.reduce_mean((Y-Hypothesis)*(Y-Hypothesis))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)##############

### 1st-2

In [6]:
learning_rate = 0.00000001##############

n_InputUnit = 4
n_1stHiddenUnit=30
n_2ndHiddenUnit=30
n_3rdHiddenUnit=50
n_4thHiddenUnit=50
n_OutputUnit = 1

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.01))    ########       
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.01))########      
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.01))########      
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_4thHiddenUnit],stddev=0.01))########      
W5 = tf.Variable(tf.random_normal([n_4thHiddenUnit, n_OutputUnit],stddev=0.01))   ########   

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], mean = 0, stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], mean = 0, stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], mean = 0, stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_4thHiddenUnit], mean = 0, stddev=0.01))
b5 = tf.Variable(tf.random_normal([n_OutputUnit], mean = 0, stddev=0.01))

X = tf.placeholder(tf.float32, [None, 4]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None,])
print(X)

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
Hypothesis = tf.nn.tanh(tf.matmul(L4, W5) + b5)###############

#cost = tf.reduce_mean((Y-Hypothesis)*(Y-Hypothesis))
cost = tf.reduce_mean(tf.square(Y-Hypothesis))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)#################

Tensor("Placeholder_4:0", shape=(?, 4), dtype=float32)


## 2nd

In [3]:
tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.00001

n_InputUnit = 4
n_1stHiddenUnit=20
n_2ndHiddenUnit=20
n_3rdHiddenUnit=20
n_4thHiddenUnit=20
n_5thHiddenUnit=20
n_6thHiddenUnit=20
n_7thHiddenUnit=20
n_OutputUnit = 1

W1 = tf.Variable(tf.random_normal([n_InputUnit, n_1stHiddenUnit],stddev=0.01))
W2 = tf.Variable(tf.random_normal([n_1stHiddenUnit, n_2ndHiddenUnit],stddev=0.01))
W3 = tf.Variable(tf.random_normal([n_2ndHiddenUnit, n_3rdHiddenUnit],stddev=0.01))
W4 = tf.Variable(tf.random_normal([n_3rdHiddenUnit, n_4thHiddenUnit],stddev=0.01))
W5 = tf.Variable(tf.random_normal([n_4thHiddenUnit, n_5thHiddenUnit],stddev=0.01))
W6 = tf.Variable(tf.random_normal([n_5thHiddenUnit, n_6thHiddenUnit],stddev=0.01))
W7 = tf.Variable(tf.random_normal([n_6thHiddenUnit, n_7thHiddenUnit],stddev=0.01))
W8 = tf.Variable(tf.random_normal([n_7thHiddenUnit, n_OutputUnit],stddev=0.01))

b1 = tf.Variable(tf.random_normal([n_1stHiddenUnit], stddev=0.01))
b2 = tf.Variable(tf.random_normal([n_2ndHiddenUnit], stddev=0.01))
b3 = tf.Variable(tf.random_normal([n_3rdHiddenUnit], stddev=0.01))
b4 = tf.Variable(tf.random_normal([n_4thHiddenUnit], stddev=0.01))
b5 = tf.Variable(tf.random_normal([n_5thHiddenUnit], stddev=0.01))
b6 = tf.Variable(tf.random_normal([n_6thHiddenUnit], stddev=0.01))
b7 = tf.Variable(tf.random_normal([n_7thHiddenUnit], stddev=0.01))
b8 = tf.Variable(tf.random_normal([n_OutputUnit], stddev=0.01))

X = tf.placeholder(tf.float32, [None, 4]) # tensorflow의 placeholder라는 변수를 선언
Y = tf.placeholder(tf.float32, [None,])

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
L5 = tf.nn.relu(tf.matmul(L4, W5) + b5)
L6 = tf.nn.relu(tf.matmul(L5, W6) + b6)
L7 = tf.nn.relu(tf.matmul(L6, W7) + b7)
Hypothesis = tf.nn.tanh(tf.matmul(L7, W8) + b8)

cost = tf.reduce_mean((Y-Hypothesis)*(Y-Hypothesis))
train = tf.train.AdamOptimizer(learning_rate, beta1 = 0.01, beta2 = 0.1).minimize(cost)#######

# Train NN & Predict

In [4]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    
    for step in range(300000):
        SGDorder = Sequence[step % 21] # training을 0번부터 23번까지 순차적으로 돌린다.
        session.run(train, feed_dict ={X: X_TrainingData[SGDorder: SGDorder + 1,:], Y: Y_TrainingData[SGDorder: SGDorder + 1]})
        #session.run(train, feed_dict ={X: X_TrainingData, Y: Y_TrainingData})
        
        if step % 1000 == 0:
            print (SGDorder,step, session.run(cost, feed_dict = {X: X_TrainingData, Y: Y_TrainingData}))
            #print (W1)
            #print (b1)
        if step % 21 == 0:
            random.shuffle(Sequence)
            
    Predict_to_TestData = session.run(Hypothesis, feed_dict={X : X_TestData})
    Predict_to_TrainingData = session.run(Hypothesis, feed_dict={X : X_TrainingData})
    Predict_to_EntireData = session.run(Hypothesis, feed_dict = {X : X_NormalizedData})
    
    print("R_square")
    print(r2_score(Y_NormalizedData, Predict_to_EntireData))
    print("Result of predicting TrainingData")
    print((Predict_to_TrainingData * (max(Y_OriginalData)-min(Y_OriginalData))) + np.mean(Y_OriginalData))
    print("Result of predicting TestData")
    print((Predict_to_TestData * (max(Y_OriginalData)-min(Y_OriginalData))) + np.mean(Y_OriginalData))
    print("Original Data")
    print(Y_OriginalData)

0 0 0.0539598
7 1000 0.0539104
9 2000 0.0538642
4 3000 0.0538238
0 4000 0.0537881
5 5000 0.0537555
4 6000 0.0537298
20 7000 0.0537051
3 8000 0.0536858
5 9000 0.0536692
15 10000 0.0536551
10 11000 0.0536452
19 12000 0.0536389
13 13000 0.0536346
12 14000 0.0536327
13 15000 0.0536334
10 16000 0.0536361
16 17000 0.0536412
20 18000 0.053648
18 19000 0.0536565
7 20000 0.0536678
17 21000 0.0536791
3 22000 0.0536919
0 23000 0.0537049
14 24000 0.0537207
10 25000 0.0537374
7 26000 0.0537541
9 27000 0.0537702
9 28000 0.0537865
16 29000 0.0538033
11 30000 0.0538236
15 31000 0.053846
9 32000 0.0538642
6 33000 0.0538812
1 34000 0.0539002
12 35000 0.0539156
9 36000 0.0539335
18 37000 0.0539505
10 38000 0.053968
10 39000 0.0539885
14 40000 0.0540027
17 41000 0.0540154
6 42000 0.0540387
19 43000 0.0540526
16 44000 0.0540632
0 45000 0.0540796
2 46000 0.0540923
1 47000 0.0541067
14 48000 0.0541197
11 49000 0.0541288
8 50000 0.0541446
16 51000 0.0541576
11 52000 0.0541728
15 53000 0.0541841
12 54000 0.054