In [7]:
import torch

In [8]:
N, D = 3, 4

In [19]:
x = torch.randn(N, D, requires_grad = True)
y = torch.randn(N, D)
z = torch.randn(N, D)
print(x)

tensor([[ 0.1247, -0.6511,  0.2216, -0.8651],
        [-0.5421, -1.3812, -1.3220, -1.1425],
        [ 0.2216,  0.5287, -0.8992,  0.1429]], requires_grad=True)


In [22]:
a = x * y
b = a + z
c = torch.sum(b) # Sum of components of b

tensor([[ 1.6663, -2.5761, -1.4655,  2.9808],
        [ 0.2708, -0.0437,  1.9448, -0.0183],
        [ 0.8066,  0.1986,  0.6666, -1.8908]], grad_fn=<ThAddBackward>) tensor(2.5402, grad_fn=<SumBackward0>)


In [11]:
c.backward()
print(x.grad)

tensor([[-0.0336, -1.2903, -0.8029,  1.0269],
        [-0.4439,  1.5540, -0.0196,  1.2345],
        [ 1.1173,  1.2256, -0.3272,  0.2248]])


In [28]:
d = torch.tensor([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])

In [30]:
e = torch.sum(d)
print(e)

tensor(24)
