In [10]:
import torch

In [11]:
N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
w1 = torch.randn(D_in, H, requires_grad = True)
w2 = torch.randn(H, D_out, requires_grad = True)

In [12]:
learning_rate = 1e-6

In [13]:
for t in range (500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    loss = (y_pred - y).pow(2).sum()
    print(w1)

tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        

tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        

tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        

tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        

tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        [ 0.9137, -0.2125, -0.3232,  ...,  0.5634, -1.2792,  0.0599],
        [-0.0394, -0.6741, -0.9065,  ...,  0.3690, -2.5795, -0.0327],
        ...,
        [-1.7464, -0.8530, -0.2527,  ..., -0.2223,  1.5891,  0.5064],
        [-0.4385, -0.7487,  0.6109,  ..., -0.6695,  0.4602,  0.3747],
        [ 1.3178,  0.2606, -0.4308,  ...,  2.2535,  2.0555,  0.5445]],
       requires_grad=True)
tensor([[ 1.8053,  0.3797,  0.2393,  ...,  1.5498, -1.1687,  1.5427],
        

In [14]:
loss.backward()

In [15]:
with torch.no_grad():
    w1 -= learning_rate * w1.grad
    w2 -= learning_rate * w2.grad
    w1.grad.zero_()
    w2.grad.zero_()

In [7]:
print(w1)

tensor([[-1.3226, -0.1023,  1.8242,  ...,  0.3841,  1.5591,  0.3933],
        [ 1.9213, -0.5483, -0.0446,  ..., -0.0168, -1.5862,  0.5785],
        [-0.2732,  0.9607, -0.9450,  ..., -0.4137, -0.1116,  1.5151],
        ...,
        [ 1.1563, -0.0962, -1.0260,  ..., -0.4342, -0.0943, -1.0380],
        [-0.1386, -0.2889, -1.7302,  ...,  0.0991, -1.3829,  0.6824],
        [ 1.8697, -0.5446, -0.0593,  ..., -0.7598,  0.0647, -0.6109]],
       requires_grad=True)


In [8]:
print(w2)

tensor([[-0.5305,  1.5766,  0.7089, -0.5548,  0.3538,  1.2523,  0.2720,  0.8496,
          0.9176,  0.9447],
        [-1.1318,  1.0396,  0.5208, -0.7885,  0.7615,  1.5654,  0.5589, -0.6473,
          0.0401,  0.3477],
        [ 0.2506,  0.7918, -0.2662,  0.9478,  0.3101, -2.1689,  0.4807,  0.7049,
          1.4251,  0.9496],
        [ 0.7101, -1.3638, -1.6135,  0.4192, -1.4753,  0.7889, -0.5789, -0.8927,
          0.3148,  0.4171],
        [ 0.7252, -0.5010, -0.3007,  0.4367,  0.2132,  0.6718,  0.0929,  0.4608,
         -0.0812,  1.2093],
        [ 0.8789,  0.2485,  1.1287, -0.7081, -0.5414, -0.5546, -1.1401, -1.2407,
         -0.4630, -0.9281],
        [-0.5602,  0.4195, -0.0943,  0.9236,  0.5618, -0.3948,  0.0314, -0.4362,
         -1.0830, -0.7180],
        [ 0.7407,  0.1119,  0.1028, -1.3954,  0.3367, -0.1323,  1.7244,  0.2123,
          0.8420,  1.0361],
        [ 0.0585, -0.7944,  0.9140, -0.7691, -0.7866,  0.5690, -0.8233, -1.0730,
          1.0462, -2.1614],
        [ 0.3666, -